// GENERATED by build-prod-replica-seed.cjs — do not edit by hand.
// Exact replica of the production seller roster (seller-portal.bms.qwipo.com)
// as of 2026-08-12: real names, phone numbers and business names, so local
// customer exports map 1:1 onto production sellers.
import type { Seller } from "./mock-store";

export const PROD_REPLICA_SELLERS: Seller[] = [
  {
    "id": "seller-prod-banjara",
    "name": "JHARAPLA SAROJA",
    "email": "prod-8688340270@qwipo.com",
    "phone": "8688340270",
    "businessName": "BANJARA MARKETING",
    "city": "Hyderabad City",
    "pinCode": "500018",
    "state": "Telangana",
    "latitude": 17.4575559,
    "longitude": 78.4275848,
    "fullAddress": "8-4-336/1/G, Banjaranagar, Erragadda, Hyderabad, Telangana, 500018.",
    "isActive": true,
    "sellerType": "distributor",
    "kyc": {
      "gstin": "36ODCPS3159F1Z4",
      "businessAddress": "8-4-336/1/G, Banjaranagar, Erragadda, Hyderabad, Telangana, 500018.",
      "status": "verified",
      "updatedAt": "2026-07-17T00:00:00Z"
    },
    "connectors": {
      "bizom": {
        "status": "not_connected"
      },
      "ondc": {
        "status": "not_connected"
      }
    },
    "permissions": {
      "view": true,
      "write": true,
      "edit": true,
      "update": true
    },
    "managedCompanies": [
      "co-prod-swastik-mirch-store"
    ],
    "companyBrandSelections": [],
    "approvedAt": "2026-07-17T00:00:00Z"
  },
  {
    "id": "seller-prod-skm",
    "name": "JALIGUM VIJAYA LAKSHMI",
    "email": "prod-9985229232@qwipo.com",
    "phone": "9985229232",
    "businessName": "SKM ENTERPRISES",
    "city": "Hyderabad City",
    "pinCode": "500018",
    "state": "Telangana",
    "latitude": 17.453823,
    "longitude": 78.4406493,
    "fullAddress": "H NO SRT 794, SANATH NAGAR, NEAR BY VEGETABLE MARKET, HYDERABAD.",
    "isActive": true,
    "sellerType": "distributor",
    "kyc": {
      "gstin": "36BPJPJ3686QIZZ",
      "businessAddress": "H NO SRT 794, SANATH NAGAR, NEAR BY VEGETABLE MARKET, HYDERABAD.",
      "status": "verified",
      "updatedAt": "2026-07-17T00:00:00Z"
    },
    "connectors": {
      "bizom": {
        "status": "not_connected"
      },
      "ondc": {
        "status": "not_connected"
      }
    },
    "permissions": {
      "view": true,
      "write": true,
      "edit": true,
      "update": true
    },
    "managedCompanies": [
      "co-prod-anoos-electrolysis-and-obesity-pvt-ltd",
      "co-prod-apis-india-limited",
      "co-prod-aravind-laboratories",
      "co-prod-argus-cosmetics-limited",
      "co-prod-aswini-homeo-and-ayurvedic-products-pvt-",
      "co-prod-dey-s-medical-stores-pvt-ltd",
      "co-prod-dodla-dairy-limited",
      "co-prod-henna-industries-pvt-ltd",
      "co-prod-karnataka-soaps-and-detergents-limited",
      "co-prod-mayuri-chemicals-private-limited",
      "co-prod-parimal-mandir",
      "co-prod-rkrm-international-products-pvt-ltd",
      "co-prod-tiesar-personal-care-pvt-ltd"
    ],
    "companyBrandSelections": [],
    "approvedAt": "2026-07-17T00:00:00Z"
  },
  {
    "id": "seller-prod-balaji-trading",
    "name": "VANSH AGARWAL",
    "email": "prod-7702002017@qwipo.com",
    "phone": "7702002017",
    "businessName": "BALAJI TRADING",
    "city": "Hyderabad City",
    "pinCode": "500018",
    "state": "Telangana",
    "latitude": 17.4649943,
    "longitude": 78.4210894,
    "fullAddress": "FATIMA WAREHOUSING COMPLEX, Railway Goods Shed Road, Moosapet, Telangana 500018",
    "isActive": true,
    "sellerType": "distributor",
    "kyc": {
      "gstin": "36DXKPA9903G1ZE",
      "businessAddress": "FATIMA WAREHOUSING COMPLEX, Railway Goods Shed Road, Moosapet, Telangana 500018",
      "status": "verified",
      "updatedAt": "2026-07-17T00:00:00Z"
    },
    "connectors": {
      "bizom": {
        "status": "not_connected"
      },
      "ondc": {
        "status": "not_connected"
      }
    },
    "permissions": {
      "view": true,
      "write": true,
      "edit": true,
      "update": true
    },
    "managedCompanies": [
      "co-freedom"
    ],
    "companyBrandSelections": [],
    "approvedAt": "2026-07-17T00:00:00Z"
  },
  {
    "id": "seller-prod-silpatwal",
    "name": "NARESH RAMAVTAR GUPTA",
    "email": "prod-9821253909@qwipo.com",
    "phone": "9821253909",
    "businessName": "SILPATWAL TRADERS",
    "city": "Mumbai North West",
    "pinCode": "400092",
    "state": "Maharashtra",
    "latitude": 19.253941,
    "longitude": 72.849579,
    "fullAddress": "Bldg No.1 B Wing, Shop No-2, Golders Green,Maharashtra Holly Cross Road, Borivali West Mumbai - 400092",
    "isActive": true,
    "sellerType": "distributor",
    "kyc": {
      "gstin": "27AECPG0304H1Z6",
      "businessAddress": "Bldg No.1 B Wing, Shop No-2, Golders Green,Maharashtra Holly Cross Road, Borivali West Mumbai - 400092",
      "status": "verified",
      "updatedAt": "2026-07-17T00:00:00Z"
    },
    "connectors": {
      "bizom": {
        "status": "not_connected"
      },
      "ondc": {
        "status": "not_connected"
      }
    },
    "permissions": {
      "view": true,
      "write": true,
      "edit": true,
      "update": true
    },
    "managedCompanies": [
      "co-prod-b-p-oil-mills-limited",
      "co-prod-aak-kamani-private-limited",
      "co-prod-ami-oil-mill",
      "co-prod-bolas-agro-private-limited",
      "co-prod-kirti-oil-industries-private-limited",
      "co-prod-kamani-oil-industries",
      "co-prod-komal-oil-private-limited",
      "co-prod-marico-limited",
      "co-prod-r-r-oomerbhoy-pvt-ltd",
      "co-prod-raj-oil-mills-ltd",
      "co-prod-vimal-oil-and-foods-ltd",
      "co-prod-vitthal-oil-industries"
    ],
    "companyBrandSelections": [],
    "approvedAt": "2026-07-17T00:00:00Z"
  },
  {
    "id": "seller-prod-jagadish",
    "name": "PADIDELA JAGDEESHWAR RAO",
    "email": "prod-9963120143@qwipo.com",
    "phone": "9963120143",
    "businessName": "JAGADISH AGENCIES",
    "city": "Hyderabad City",
    "pinCode": "500018",
    "state": "Telangana",
    "latitude": 17.458455,
    "longitude": 78.453121,
    "fullAddress": "First Floor, 10-4-70, Balanagar, Sanathnagar IE, Sri Ramalayam Mandir Entrance, Fathe Nagar, Hyderabad, Rangareddy, Telangana, 500018",
    "isActive": true,
    "sellerType": "distributor",
    "kyc": {
      "gstin": "36BOXPP1339F1ZI",
      "businessAddress": "First Floor, 10-4-70, Balanagar, Sanathnagar IE, Sri Ramalayam Mandir Entrance, Fathe Nagar, Hyderabad, Rangareddy, Telangana, 500018",
      "status": "verified",
      "updatedAt": "2026-07-17T00:00:00Z"
    },
    "connectors": {
      "bizom": {
        "status": "not_connected"
      },
      "ondc": {
        "status": "not_connected"
      }
    },
    "permissions": {
      "view": true,
      "write": true,
      "edit": true,
      "update": true
    },
    "managedCompanies": [
      "co-prod-emami-limited"
    ],
    "companyBrandSelections": [],
    "approvedAt": "2026-07-17T00:00:00Z"
  },
  {
    "id": "seller-prod-mas-marketing",
    "name": "ABDUL HASEEB MOHAMMED",
    "email": "prod-9866198219@qwipo.com",
    "phone": "9866198219",
    "businessName": "MAS MARKETING",
    "city": "Hyderabad South East",
    "pinCode": "500048",
    "state": "Telangana",
    "latitude": 17.349871,
    "longitude": 78.414398,
    "fullAddress": "2-2-109, , UPPERPALLY, Hyderabad, 500048",
    "isActive": true,
    "sellerType": "distributor",
    "kyc": {
      "gstin": "36ASRPM7304E1ZL",
      "businessAddress": "2-2-109, , UPPERPALLY, Hyderabad, 500048",
      "status": "verified",
      "updatedAt": "2026-07-17T00:00:00Z"
    },
    "connectors": {
      "bizom": {
        "status": "not_connected"
      },
      "ondc": {
        "status": "not_connected"
      }
    },
    "permissions": {
      "view": true,
      "write": true,
      "edit": true,
      "update": true
    },
    "managedCompanies": [],
    "companyBrandSelections": [],
    "approvedAt": "2026-07-17T00:00:00Z"
  },
  {
    "id": "seller-prod-mvm-synergy",
    "name": "Mvm Synergy Solutions LLP",
    "email": "prod-9970169334@qwipo.com",
    "phone": "9970169334",
    "businessName": "Mvm Synergy Solutions LLP",
    "city": "Thane West",
    "pinCode": "401105",
    "state": "Maharashtra",
    "latitude": 19.316502,
    "longitude": 72.85524,
    "fullAddress": "A-15 New Samir Chs Ltd K-7,Jesal Park,B Patil Road,Bhayandar East,Thane,401105",
    "isActive": true,
    "sellerType": "distributor",
    "kyc": {
      "gstin": "27ACGFM0411P1Z4",
      "businessAddress": "A-15 New Samir Chs Ltd K-7,Jesal Park,B Patil Road,Bhayandar East,Thane,401105",
      "status": "verified",
      "updatedAt": "2026-07-17T00:00:00Z"
    },
    "connectors": {
      "bizom": {
        "status": "not_connected"
      },
      "ondc": {
        "status": "not_connected"
      }
    },
    "permissions": {
      "view": true,
      "write": true,
      "edit": true,
      "update": true
    },
    "managedCompanies": [
      "co-prod-mvm-synergy-solutions-llp"
    ],
    "companyBrandSelections": [],
    "approvedAt": "2026-07-17T00:00:00Z"
  },
  {
    "id": "seller-prod-gurukumaran",
    "name": "Ms Gurukumaran Nadar",
    "email": "prod-9819139532@qwipo.com",
    "phone": "9819139532",
    "businessName": "Ms Gurukumaran Nadar",
    "city": "Mumbai North West",
    "pinCode": "400067",
    "state": "Maharashtra",
    "latitude": 19.215591,
    "longitude": 72.852287,
    "fullAddress": "Shop No 2,Krishna Apt. Chs.Ltd.Cst No.6/A,Bhatt Lane,Kandivali West,Mumbai-400067",
    "isActive": true,
    "sellerType": "distributor",
    "kyc": {
      "gstin": "37AAACX1706A1ZY",
      "businessAddress": "Shop No 2,Krishna Apt. Chs.Ltd.Cst No.6/A,Bhatt Lane,Kandivali West,Mumbai-400067",
      "status": "verified",
      "updatedAt": "2026-07-17T00:00:00Z"
    },
    "connectors": {
      "bizom": {
        "status": "not_connected"
      },
      "ondc": {
        "status": "not_connected"
      }
    },
    "permissions": {
      "view": true,
      "write": true,
      "edit": true,
      "update": true
    },
    "managedCompanies": [
      "co-prod-western-india-bakers-pvt-ltd"
    ],
    "companyBrandSelections": [],
    "approvedAt": "2026-07-17T00:00:00Z"
  },
  {
    "id": "seller-prod-yln",
    "name": "UNNIKRISHNA KASAM",
    "email": "prod-9030456547@qwipo.com",
    "phone": "9030456547",
    "businessName": "YLN AGENCIES",
    "city": "Hyderabad South East",
    "pinCode": "500074",
    "state": "Telangana",
    "latitude": 17.338726,
    "longitude": 78.55168,
    "fullAddress": "7-4-26, Biramalguda, Saroor Nagar Mandal, Hyderabad, Rangareddy, Telangana, 500074",
    "isActive": true,
    "sellerType": "distributor",
    "kyc": {
      "gstin": "36AABFY9700C1ZB",
      "businessAddress": "7-4-26, Biramalguda, Saroor Nagar Mandal, Hyderabad, Rangareddy, Telangana, 500074",
      "status": "verified",
      "updatedAt": "2026-07-17T00:00:00Z"
    },
    "connectors": {
      "bizom": {
        "status": "not_connected"
      },
      "ondc": {
        "status": "not_connected"
      }
    },
    "permissions": {
      "view": true,
      "write": true,
      "edit": true,
      "update": true
    },
    "managedCompanies": [],
    "companyBrandSelections": [],
    "approvedAt": "2026-07-17T00:00:00Z"
  },
  {
    "id": "seller-prod-jai-ganesh",
    "name": "POLAPAKA RUPESH KUMAR",
    "email": "prod-9985633229@qwipo.com",
    "phone": "9985633229",
    "businessName": "JAI GANESH AGENCIES",
    "city": "Secunderabad",
    "pinCode": "500062",
    "state": "Telangana",
    "latitude": 17.474239,
    "longitude": 78.547992,
    "fullAddress": "H.NO 30-265/8/83/1, Geetha nagar, road no 2, AS Rao Nagar",
    "isActive": true,
    "sellerType": "distributor",
    "kyc": {
      "gstin": "36BBTPK2286H1Z6",
      "businessAddress": "H.NO 30-265/8/83/1, Geetha nagar, road no 2, AS Rao Nagar",
      "status": "verified",
      "updatedAt": "2026-07-17T00:00:00Z"
    },
    "connectors": {
      "bizom": {
        "status": "not_connected"
      },
      "ondc": {
        "status": "not_connected"
      }
    },
    "permissions": {
      "view": true,
      "write": true,
      "edit": true,
      "update": true
    },
    "managedCompanies": [
      "co-prod-emami-limited"
    ],
    "companyBrandSelections": [],
    "approvedAt": "2026-07-17T00:00:00Z"
  },
  {
    "id": "seller-prod-dev",
    "name": "ASHOK PAREEK",
    "email": "prod-8500011128@qwipo.com",
    "phone": "8500011128",
    "businessName": "DEV AGENCIES",
    "city": "Hyderabad City",
    "pinCode": "500019",
    "state": "Telangana",
    "latitude": 17.5033618,
    "longitude": 78.3070492,
    "fullAddress": "H.No. 3-33/19, Venkata Reddy Colony, Taranagar, Serilingampally, Hyderabad, Ranga Reddy, Telangana - 500019",
    "isActive": true,
    "sellerType": "distributor",
    "kyc": {
      "gstin": "36AKVPP3365L1ZA",
      "businessAddress": "H.No. 3-33/19, Venkata Reddy Colony, Taranagar, Serilingampally, Hyderabad, Ranga Reddy, Telangana - 500019",
      "status": "verified",
      "updatedAt": "2026-07-17T00:00:00Z"
    },
    "connectors": {
      "bizom": {
        "status": "not_connected"
      },
      "ondc": {
        "status": "not_connected"
      }
    },
    "permissions": {
      "view": true,
      "write": true,
      "edit": true,
      "update": true
    },
    "managedCompanies": [
      "co-prod-colgate-palmolive"
    ],
    "companyBrandSelections": [],
    "approvedAt": "2026-07-17T00:00:00Z"
  },
  {
    "id": "seller-prod-jsv",
    "name": "AMARNATH PALLA",
    "email": "prod-9440665515@qwipo.com",
    "phone": "9440665515",
    "businessName": "J S V MARKETING",
    "city": "Hyderabad City",
    "pinCode": "500018",
    "state": "Telangana",
    "latitude": 17.451225,
    "longitude": 78.448068,
    "fullAddress": "7-2-590, SRT 369",
    "isActive": true,
    "sellerType": "distributor",
    "kyc": {
      "gstin": "36AMZPP2684A1ZL",
      "businessAddress": "7-2-590, SRT 369",
      "status": "verified",
      "updatedAt": "2026-07-17T00:00:00Z"
    },
    "connectors": {
      "bizom": {
        "status": "not_connected"
      },
      "ondc": {
        "status": "not_connected"
      }
    },
    "permissions": {
      "view": true,
      "write": true,
      "edit": true,
      "update": true
    },
    "managedCompanies": [
      "co-prod-international-flavours-and-fragrances-in",
      "co-prod-lion-dates-impex-p-ltd",
      "co-prod-msk-flavours",
      "co-prod-peppergami-food-labs-private-limited",
      "co-prod-raghav-lifestyle-products",
      "co-prod-sgr-777-foods-private-limited",
      "co-prod-weikfield-foods-private-limited"
    ],
    "companyBrandSelections": [],
    "approvedAt": "2026-07-17T00:00:00Z"
  },
  {
    "id": "seller-prod-dhhana-laxme",
    "name": "VENKATA SHIVAJI VANAMA",
    "email": "prod-9866781539@qwipo.com",
    "phone": "9866781539",
    "businessName": "DHHANA LAXME ENTERPRISES",
    "city": "Hyderabad City",
    "pinCode": "500038",
    "state": "Telangana",
    "latitude": 17.445655,
    "longitude": 78.445282,
    "fullAddress": "7-1-621/542, PLOT NO 216A, BK GUDA, SR NAGAR",
    "isActive": true,
    "sellerType": "distributor",
    "kyc": {
      "gstin": "36AFPPV0738N1ZM",
      "businessAddress": "7-1-621/542, PLOT NO 216A, BK GUDA, SR NAGAR",
      "status": "verified",
      "updatedAt": "2026-07-17T00:00:00Z"
    },
    "connectors": {
      "bizom": {
        "status": "not_connected"
      },
      "ondc": {
        "status": "not_connected"
      }
    },
    "permissions": {
      "view": true,
      "write": true,
      "edit": true,
      "update": true
    },
    "managedCompanies": [
      "co-prod-3f-industries-ltd",
      "co-adani",
      "co-prod-emami-agrotech-limited",
      "co-prod-fourtune-agri-solutions",
      "co-prod-healthy-heart-foods",
      "co-prod-kedia-agro",
      "co-prod-magnum-enterprises",
      "co-prod-navabhart-limited",
      "co-prod-patanjali-foods-limited",
      "co-prod-pattabi-agro-foods-pvt-ltd",
      "co-prod-santhoshimatha-edible-oils-refinery-pvt-",
      "co-prod-shree-gajanan-industries",
      "co-prod-sri-tulasi-industries"
    ],
    "companyBrandSelections": [],
    "approvedAt": "2026-07-17T00:00:00Z"
  },
  {
    "id": "seller-prod-vinodh",
    "name": "VINODH MUTTINENI",
    "email": "prod-9493018641@qwipo.com",
    "phone": "9493018641",
    "businessName": "VINODH ENTERPRISES",
    "city": "Secunderabad",
    "pinCode": "500055",
    "state": "Telangana",
    "latitude": 17.509018,
    "longitude": 78.32085,
    "fullAddress": "HUDA COLONY, 13-81/1, MIG 459, CHANDANAGAR, HYDERABAD, Ranga Reddy, Telangana, 500055",
    "isActive": true,
    "sellerType": "distributor",
    "kyc": {
      "gstin": "36AJFPV0935P1ZK",
      "businessAddress": "HUDA COLONY, 13-81/1, MIG 459, CHANDANAGAR, HYDERABAD, Ranga Reddy, Telangana, 500055",
      "status": "verified",
      "updatedAt": "2026-07-17T00:00:00Z"
    },
    "connectors": {
      "bizom": {
        "status": "not_connected"
      },
      "ondc": {
        "status": "not_connected"
      }
    },
    "permissions": {
      "view": true,
      "write": true,
      "edit": true,
      "update": true
    },
    "managedCompanies": [
      "co-prod-himalaya-wellness-company",
      "co-prod-vanesa-care-pvt-ltd",
      "co-prod-wipro-enterprises-p-limited"
    ],
    "companyBrandSelections": [],
    "approvedAt": "2026-07-17T00:00:00Z"
  },
  {
    "id": "seller-prod-shalvi",
    "name": "Shalvi Mumbai Seller",
    "email": "prod-8329996029@qwipo.com",
    "phone": "8329996029",
    "businessName": "Shalvi Mumbai Seller",
    "city": "Mumbai North West",
    "pinCode": "400092",
    "state": "Maharashtra",
    "latitude": 19.22448,
    "longitude": 72.84594,
    "fullAddress": "Wamanrao Pai Garden, TPS Rd, Rameshwar Darshan CHS, Babhai Naka, Borivali West",
    "isActive": true,
    "sellerType": "distributor",
    "kyc": {
      "gstin": "37AAACX1706A1ZW",
      "businessAddress": "Wamanrao Pai Garden, TPS Rd, Rameshwar Darshan CHS, Babhai Naka, Borivali West",
      "status": "verified",
      "updatedAt": "2026-07-17T00:00:00Z"
    },
    "connectors": {
      "bizom": {
        "status": "not_connected"
      },
      "ondc": {
        "status": "not_connected"
      }
    },
    "permissions": {
      "view": true,
      "write": true,
      "edit": true,
      "update": true
    },
    "managedCompanies": [],
    "companyBrandSelections": [],
    "approvedAt": "2026-07-17T00:00:00Z"
  },
  {
    "id": "seller-prod-chaswi",
    "name": "GAYATHRI VALLURI",
    "email": "prod-9989998536@qwipo.com",
    "phone": "9989998536",
    "businessName": "CHASWI MARKETING SOLUTIONS",
    "city": "Secunderabad",
    "pinCode": "500050",
    "state": "Telangana",
    "latitude": 17.4866371,
    "longitude": 78.32127,
    "fullAddress": "HUDAFACE-2, 6-94/249, NEAR TO PJR STADIUM, CHANDANAGAR, Ranga Reddy, Telangana, 500050",
    "isActive": true,
    "sellerType": "distributor",
    "kyc": {
      "gstin": "36ANXPV7185M1ZK",
      "businessAddress": "HUDAFACE-2, 6-94/249, NEAR TO PJR STADIUM, CHANDANAGAR, Ranga Reddy, Telangana, 500050",
      "status": "verified",
      "updatedAt": "2026-07-17T00:00:00Z"
    },
    "connectors": {
      "bizom": {
        "status": "not_connected"
      },
      "ondc": {
        "status": "not_connected"
      }
    },
    "permissions": {
      "view": true,
      "write": true,
      "edit": true,
      "update": true
    },
    "managedCompanies": [
      "co-prod-aadishwar-organics-private-limited",
      "co-prod-adyar-ananda-bhavan-sweets-india-private",
      "co-prod-allied-natural-product",
      "co-prod-ambica-agarbathies-aroma-and-industries-",
      "co-prod-aswini-homeo-and-ayurvedic-products-pvt-",
      "co-prod-buy-happy-marketing-llp",
      "co-prod-dey-s-medical-stores-pvt-ltd",
      "co-prod-duracell-inc",
      "co-prod-dwibhashi-bapanna-ayurveda-nilayam-pvt-l",
      "co-prod-harvesta-farming-private-limited",
      "co-prod-haw-par-healthcare-limited",
      "co-prod-hygienic-research-institute-private-limi",
      "co-prod-laljee-godhoo-and-co",
      "co-prod-mayuri-chemicals-private-limited",
      "co-prod-midas-hygiene-industries-pvt-ltd",
      "co-prod-nextg-apex-india-pvt-ltd",
      "co-prod-sachin-traders",
      "co-prod-sesa-care-pvt-ltd",
      "co-prod-the-national-tea-depot",
      "co-prod-vicco-laboratories",
      "co-prod-vijaya-chemicals-and-toilet-works-telang"
    ],
    "companyBrandSelections": [],
    "approvedAt": "2026-07-17T00:00:00Z"
  },
  {
    "id": "seller-prod-lakshmi-saai",
    "name": "PRAVEEN KUMAR VENNU",
    "email": "prod-8519877717@qwipo.com",
    "phone": "8519877717",
    "businessName": "LAKSHMI SAAI ENTERPRISES",
    "city": "Secunderabad",
    "pinCode": "500054",
    "state": "Telangana",
    "latitude": 17.4862465,
    "longitude": 17.4862465,
    "fullAddress": "7 100/28, RAMAKRISHNA NAGAR, CHINTAL, Medchal - Malkajgiri, Telangana, 500054",
    "isActive": false,
    "sellerType": "distributor",
    "kyc": {
      "gstin": "36AWYPV1343D1Z4",
      "businessAddress": "7 100/28, RAMAKRISHNA NAGAR, CHINTAL, Medchal - Malkajgiri, Telangana, 500054",
      "status": "verified",
      "updatedAt": "2026-07-17T00:00:00Z"
    },
    "connectors": {
      "bizom": {
        "status": "not_connected"
      },
      "ondc": {
        "status": "not_connected"
      }
    },
    "permissions": {
      "view": true,
      "write": true,
      "edit": true,
      "update": true
    },
    "managedCompanies": [
      "co-prod-grb-dairy-foods-pvt-ltd",
      "co-prod-marino-food-products-pvt-ltd",
      "co-prod-sln-coffee-pvt-ltd"
    ],
    "companyBrandSelections": [],
    "approvedAt": "2026-07-17T00:00:00Z"
  },
  {
    "id": "seller-prod-sahasra",
    "name": "DIVYA GOGINENI",
    "email": "prod-9948028989@qwipo.com",
    "phone": "9948028989",
    "businessName": "SAHASRA ENTERPRISES",
    "city": "Secunderabad",
    "pinCode": "500072",
    "state": "Telangana",
    "latitude": 17.505048,
    "longitude": 78.414073,
    "fullAddress": "H. No. 432-1135-A164, Phase-2, Allwyn Colony, Kukatpally, Hyderabad, Medchal Malkajgiri, Telangana - 500072",
    "isActive": true,
    "sellerType": "distributor",
    "kyc": {
      "gstin": "36AVFPG1187N1Z9",
      "businessAddress": "H. No. 432-1135-A164, Phase-2, Allwyn Colony, Kukatpally, Hyderabad, Medchal Malkajgiri, Telangana - 500072",
      "status": "verified",
      "updatedAt": "2026-07-17T00:00:00Z"
    },
    "connectors": {
      "bizom": {
        "status": "not_connected"
      },
      "ondc": {
        "status": "not_connected"
      }
    },
    "permissions": {
      "view": true,
      "write": true,
      "edit": true,
      "update": true
    },
    "managedCompanies": [
      "co-prod-swastiks-masalas-pickles-and-food-produc"
    ],
    "companyBrandSelections": [],
    "approvedAt": "2026-07-17T00:00:00Z"
  },
  {
    "id": "seller-prod-ss-ent",
    "name": "Didigam Pavani",
    "email": "prod-9346605566@qwipo.com",
    "phone": "9346605566",
    "businessName": "SS Enterprises",
    "city": "Secunderabad",
    "pinCode": "500037",
    "state": "Telangana",
    "latitude": 17.501496,
    "longitude": 78.430619,
    "fullAddress": "36-88/4, Devamma Basthi, Near Swathi Vidhya Nikethan, Jagathgiri Gutta, Hyderabad, Medchal Malkajgiri, Telangana, 500037",
    "isActive": true,
    "sellerType": "distributor",
    "kyc": {
      "gstin": "36ARQPP4829B1ZJ",
      "businessAddress": "36-88/4, Devamma Basthi, Near Swathi Vidhya Nikethan, Jagathgiri Gutta, Hyderabad, Medchal Malkajgiri, Telangana, 500037",
      "status": "verified",
      "updatedAt": "2026-07-17T00:00:00Z"
    },
    "connectors": {
      "bizom": {
        "status": "not_connected"
      },
      "ondc": {
        "status": "not_connected"
      }
    },
    "permissions": {
      "view": true,
      "write": true,
      "edit": true,
      "update": true
    },
    "managedCompanies": [
      "co-prod-milky-mist-dairy-food-limited"
    ],
    "companyBrandSelections": [],
    "approvedAt": "2026-07-17T00:00:00Z"
  },
  {
    "id": "seller-prod-ss-dist",
    "name": "VENKATESHWARLU DIDIGAM",
    "email": "prod-9866444344@qwipo.com",
    "phone": "9866444344",
    "businessName": "SS DISTRIBUTORS",
    "city": "Secunderabad",
    "pinCode": "500037",
    "state": "Telangana",
    "latitude": 17.501496,
    "longitude": 78.430621,
    "fullAddress": "H.No. 36-88/4, Road Number 3, Devamma Basthi, Near Swathi Vidhyanikethan, Quthbullapur, Jagathgirigutta, Hyderabad, Medchal Malkajgiri, Telangana, 500037",
    "isActive": true,
    "sellerType": "distributor",
    "kyc": {
      "gstin": "36AFSFS1308E1ZY",
      "businessAddress": "H.No. 36-88/4, Road Number 3, Devamma Basthi, Near Swathi Vidhyanikethan, Quthbullapur, Jagathgirigutta, Hyderabad, Medchal Malkajgiri, Telangana, 500037",
      "status": "verified",
      "updatedAt": "2026-07-17T00:00:00Z"
    },
    "connectors": {
      "bizom": {
        "status": "not_connected"
      },
      "ondc": {
        "status": "not_connected"
      }
    },
    "permissions": {
      "view": true,
      "write": true,
      "edit": true,
      "update": true
    },
    "managedCompanies": [
      "co-prod-rudra-industries",
      "co-prod-reliance-consumer-products-limited-rcpl",
      "co-prod-gujarat-tea-processors-and-packers-ltd",
      "co-prod-hamdard-foods-india"
    ],
    "companyBrandSelections": [],
    "approvedAt": "2026-07-17T00:00:00Z"
  },
  {
    "id": "seller-prod-rm-traders",
    "name": "Chintha Raja Mouli",
    "email": "prod-9246172889@qwipo.com",
    "phone": "9246172889",
    "businessName": "RM Traders",
    "city": "Secunderabad",
    "pinCode": "500072",
    "state": "Telangana",
    "latitude": 17.486168,
    "longitude": 78.397041,
    "fullAddress": "MIG-736/A, Opp. 724, KPHB, Kukatpally, Hyderabad - 500072",
    "isActive": true,
    "sellerType": "distributor",
    "kyc": {
      "gstin": "36AFTPC7788R1Z5",
      "businessAddress": "MIG-736/A, Opp. 724, KPHB, Kukatpally, Hyderabad - 500072",
      "status": "verified",
      "updatedAt": "2026-07-17T00:00:00Z"
    },
    "connectors": {
      "bizom": {
        "status": "not_connected"
      },
      "ondc": {
        "status": "not_connected"
      }
    },
    "permissions": {
      "view": true,
      "write": true,
      "edit": true,
      "update": true
    },
    "managedCompanies": [
      "co-prod-lion-dates-impex-p-ltd",
      "co-prod-sri-gantasala-foods"
    ],
    "companyBrandSelections": [],
    "approvedAt": "2026-07-17T00:00:00Z"
  },
  {
    "id": "seller-prod-omkar",
    "name": "Omkar Distributor",
    "email": "prod-7773991199@qwipo.com",
    "phone": "7773991199",
    "businessName": "Omkar Test Distributor",
    "city": "Secunderabad",
    "pinCode": "500072",
    "state": "Telangana",
    "latitude": 17.4802,
    "longitude": 78.4171,
    "fullAddress": "H.No 15, 3rd Phase 3rd Phase, Plot No 14 & 15, Venkateshwara Swamy Temple Road, Kukatpally Housing Board Colony, 3rd Phase, KPHB Phase 2, Kukatpally, Hyderabad, Telangana 500072",
    "isActive": true,
    "sellerType": "distributor",
    "kyc": {
      "gstin": "37AAACX1705A1ZW",
      "businessAddress": "H.No 15, 3rd Phase 3rd Phase, Plot No 14 & 15, Venkateshwara Swamy Temple Road, Kukatpally Housing Board Colony, 3rd Phase, KPHB Phase 2, Kukatpally, Hyderabad, Telangana 500072",
      "status": "verified",
      "updatedAt": "2026-07-17T00:00:00Z"
    },
    "connectors": {
      "bizom": {
        "status": "not_connected"
      },
      "ondc": {
        "status": "not_connected"
      }
    },
    "permissions": {
      "view": true,
      "write": true,
      "edit": true,
      "update": true
    },
    "managedCompanies": [
      "co-prod-emami-limited"
    ],
    "companyBrandSelections": [],
    "approvedAt": "2026-07-17T00:00:00Z"
  },
  {
    "id": "seller-prod-sai-krishna",
    "name": "KAILASH CHAUDHARY",
    "email": "prod-8121062768@qwipo.com",
    "phone": "8121062768",
    "businessName": "SHRI SAI KRISHNA TRADERS",
    "city": "Secunderabad",
    "pinCode": "500072",
    "state": "Telangana",
    "latitude": 17.496161,
    "longitude": 78.41861,
    "fullAddress": "4-35-284, PLOT NO 87,88,105,106 & 107, BALKRISHNA NAGAR, NEAR INDIAN GAS GODOWN, Kukatpally, Hyderabad, Medchal Malkajgiri, Telangana, 500072",
    "isActive": true,
    "sellerType": "distributor",
    "kyc": {
      "gstin": "36AEEPC4773N1Z7",
      "businessAddress": "4-35-284, PLOT NO 87,88,105,106 & 107, BALKRISHNA NAGAR, NEAR INDIAN GAS GODOWN, Kukatpally, Hyderabad, Medchal Malkajgiri, Telangana, 500072",
      "status": "verified",
      "updatedAt": "2026-07-17T00:00:00Z"
    },
    "connectors": {
      "bizom": {
        "status": "not_connected"
      },
      "ondc": {
        "status": "not_connected"
      }
    },
    "permissions": {
      "view": true,
      "write": true,
      "edit": true,
      "update": true
    },
    "managedCompanies": [
      "co-adani",
      "co-prod-e-i-d-parry-india-ltd",
      "co-prod-gajrag-trading-co",
      "co-freedom",
      "co-prod-gokul-krishi-udyog-pvt-ltd",
      "co-prod-hitech-agricom-llp",
      "co-itc",
      "co-prod-karani-spices",
      "co-prod-karnool-rice-industries",
      "co-prod-kedia-agro",
      "co-prod-lohiya-edible-oils-pvt-ltd",
      "co-prod-mvr-industries",
      "co-prod-maha-vishnu-rice-industries"
    ],
    "companyBrandSelections": [],
    "approvedAt": "2026-07-17T00:00:00Z"
  },
  {
    "id": "seller-prod-sri-sarda",
    "name": "SARANSH AGARWAL",
    "email": "prod-7032401515@qwipo.com",
    "phone": "7032401515",
    "businessName": "SRI SARDA ENTERPRISES",
    "city": "Hyderabad City",
    "pinCode": "500018",
    "state": "Telangana",
    "latitude": 17.464923,
    "longitude": 78.421141,
    "fullAddress": "GROUND FLOOR, 12-7-20/52, FATIMA WAREHOUSING COMPLEX, Railway Goods Shed Road, IND Swift Ltd, Moosapet, Hyderabad, Medchal Malkajgiri, Telangana, 500018",
    "isActive": true,
    "sellerType": "distributor",
    "kyc": {
      "gstin": "36DDQPA6260J1ZA",
      "businessAddress": "GROUND FLOOR, 12-7-20/52, FATIMA WAREHOUSING COMPLEX, Railway Goods Shed Road, IND Swift Ltd, Moosapet, Hyderabad, Medchal Malkajgiri, Telangana, 500018",
      "status": "verified",
      "updatedAt": "2026-07-17T00:00:00Z"
    },
    "connectors": {
      "bizom": {
        "status": "not_connected"
      },
      "ondc": {
        "status": "not_connected"
      }
    },
    "permissions": {
      "view": true,
      "write": true,
      "edit": true,
      "update": true
    },
    "managedCompanies": [
      "co-adani",
      "co-prod-ambati-subbanna-and-co",
      "co-prod-kedia-agro",
      "co-prod-magnum-enterprises",
      "co-prod-lohiya-edible-oils-pvt-ltd",
      "co-prod-patanjali-ayurved-limited",
      "co-prod-shree-saraiwwalaa-aggrr-refineries-limit",
      "co-prod-santhoshimatha-edible-oils-refinery-pvt-",
      "co-prod-south-india-krishna-oil-and-fats-pvt",
      "co-prod-sri-ganesh-balaji-lakhdaatr-oil"
    ],
    "companyBrandSelections": [],
    "approvedAt": "2026-07-17T00:00:00Z"
  },
  {
    "id": "seller-prod-venkateshwara",
    "name": "SACHIN AINAPUR",
    "email": "prod-9160336789@qwipo.com",
    "phone": "9160336789",
    "businessName": "VENKATESHWARA AGENCIES",
    "city": "Secunderabad",
    "pinCode": "500072",
    "state": "Telangana",
    "latitude": 17.4907605,
    "longitude": 78.40817,
    "fullAddress": "HOUSE NO 5-5, BAGHAMEERI, KUKATPALLY VILLAGE, Medchal - Malkajgiri, Telangana, 500072",
    "isActive": true,
    "sellerType": "distributor",
    "kyc": {
      "gstin": "36AOQPA0800E2ZI",
      "businessAddress": "HOUSE NO 5-5, BAGHAMEERI, KUKATPALLY VILLAGE, Medchal - Malkajgiri, Telangana, 500072",
      "status": "verified",
      "updatedAt": "2026-07-17T00:00:00Z"
    },
    "connectors": {
      "bizom": {
        "status": "not_connected"
      },
      "ondc": {
        "status": "not_connected"
      }
    },
    "permissions": {
      "view": true,
      "write": true,
      "edit": true,
      "update": true
    },
    "managedCompanies": [
      "co-prod-ambati-subbanna-and-co",
      "co-prod-rehoboth-industries",
      "co-prod-shree-renuka-sugars-limited",
      "co-prod-sneha-farms"
    ],
    "companyBrandSelections": [],
    "approvedAt": "2026-07-17T00:00:00Z"
  },
  {
    "id": "seller-prod-mahadeva",
    "name": "DEVADASU DUDAM",
    "email": "prod-9390164462@qwipo.com",
    "phone": "9390164462",
    "businessName": "MAHADEVA ENTERPRISES",
    "city": "Secunderabad",
    "pinCode": "500072",
    "state": "Telangana",
    "latitude": 17.483253,
    "longitude": 78.419938,
    "fullAddress": "GROUND FLOOR, MIG 835, 1ST & II P, Kukatpally Main Road, KPHB Colony, Hyderabad, Medchal Malkajgiri, Telangana, 500072",
    "isActive": true,
    "sellerType": "distributor",
    "kyc": {
      "gstin": "36AAYPD6568L1ZT",
      "businessAddress": "GROUND FLOOR, MIG 835, 1ST & II P, Kukatpally Main Road, KPHB Colony, Hyderabad, Medchal Malkajgiri, Telangana, 500072",
      "status": "verified",
      "updatedAt": "2026-07-17T00:00:00Z"
    },
    "connectors": {
      "bizom": {
        "status": "not_connected"
      },
      "ondc": {
        "status": "not_connected"
      }
    },
    "permissions": {
      "view": true,
      "write": true,
      "edit": true,
      "update": true
    },
    "managedCompanies": [
      "co-prod-karkhana-zinda-tilismath-llp",
      "co-prod-orkla-india-private-limited"
    ],
    "companyBrandSelections": [],
    "approvedAt": "2026-07-17T00:00:00Z"
  },
  {
    "id": "seller-prod-s-r",
    "name": "Chintha Anusha",
    "email": "prod-8686673441@qwipo.com",
    "phone": "8686673441",
    "businessName": "S R ENTERPRISES",
    "city": "Secunderabad",
    "pinCode": "500037",
    "state": "Telangana",
    "latitude": 17.49925,
    "longitude": 78.431143,
    "fullAddress": "H.NO-36-280, Jagathgiri Gutta, Medchal Malkajgiri, Hyderabad, Telangana",
    "isActive": true,
    "sellerType": "distributor",
    "kyc": {
      "gstin": "36DCZPA0374M1Z2",
      "businessAddress": "H.NO-36-280, Jagathgiri Gutta, Medchal Malkajgiri, Hyderabad, Telangana",
      "status": "verified",
      "updatedAt": "2026-07-17T00:00:00Z"
    },
    "connectors": {
      "bizom": {
        "status": "not_connected"
      },
      "ondc": {
        "status": "not_connected"
      }
    },
    "permissions": {
      "view": true,
      "write": true,
      "edit": true,
      "update": true
    },
    "managedCompanies": [
      "co-prod-dwibhashi-bapanna-ayurveda-nilayam-pvt-l",
      "co-prod-henna-industries-pvt-ltd",
      "co-prod-karnataka-soaps-and-detergents-limited",
      "co-prod-vicco-laboratories"
    ],
    "companyBrandSelections": [],
    "approvedAt": "2026-07-17T00:00:00Z"
  },
  {
    "id": "seller-prod-sri-sairam",
    "name": "NARAYANA SWAMY DABBARA",
    "email": "prod-9666687556@qwipo.com",
    "phone": "9666687556",
    "businessName": "Sri Sairam Enterprises",
    "city": "Secunderabad",
    "pinCode": "500055",
    "state": "Telangana",
    "latitude": 17.488862,
    "longitude": 78.412379,
    "fullAddress": "SHOP NO 5, SWASTIK RESIDENCY, BAGH AMEER, KUKATPALLY, HYDERABAD, Medchal - Malkajgiri, Telangana",
    "isActive": true,
    "sellerType": "distributor",
    "kyc": {
      "gstin": "36AHBPD2014R1ZH",
      "businessAddress": "SHOP NO 5, SWASTIK RESIDENCY, BAGH AMEER, KUKATPALLY, HYDERABAD, Medchal - Malkajgiri, Telangana",
      "status": "verified",
      "updatedAt": "2026-07-17T00:00:00Z"
    },
    "connectors": {
      "bizom": {
        "status": "not_connected"
      },
      "ondc": {
        "status": "not_connected"
      }
    },
    "permissions": {
      "view": true,
      "write": true,
      "edit": true,
      "update": true
    },
    "managedCompanies": [
      "co-prod-grb-dairy-foods-pvt-ltd",
      "co-prod-n-ranga-rao-and-sons-private-limited",
      "co-prod-raghav-lifestyle-products",
      "co-prod-ushodaya-enterprises-private-limited"
    ],
    "companyBrandSelections": [],
    "approvedAt": "2026-07-17T00:00:00Z"
  },
  {
    "id": "seller-prod-internal-catalog",
    "name": "Catalog Admin",
    "email": "prod-9182855346@qwipo.com",
    "phone": "9182855346",
    "businessName": "Internal Catalog Seller",
    "city": "Hyderabad City",
    "pinCode": "500081",
    "state": "Telangana",
    "latitude": 17.448294,
    "longitude": 78.391487,
    "fullAddress": "Flat No. 404, Aakash Enclave",
    "isActive": true,
    "sellerType": "distributor",
    "kyc": {
      "gstin": "36AAACX1705A1ZY",
      "businessAddress": "Flat No. 404, Aakash Enclave",
      "status": "verified",
      "updatedAt": "2026-07-17T00:00:00Z"
    },
    "connectors": {
      "bizom": {
        "status": "not_connected"
      },
      "ondc": {
        "status": "not_connected"
      }
    },
    "permissions": {
      "view": true,
      "write": true,
      "edit": true,
      "update": true
    },
    "managedCompanies": [],
    "companyBrandSelections": [],
    "approvedAt": "2026-07-17T00:00:00Z"
  },
  {
    "id": "seller-prod-hanuman",
    "name": "KURA SRINIVAS",
    "email": "prod-9704626876@qwipo.com",
    "phone": "9704626876",
    "businessName": "HANUMAN ENTERPRISES",
    "city": "Secunderabad",
    "pinCode": "500047",
    "state": "Telangana",
    "latitude": 17.4494815,
    "longitude": 78.5330918,
    "fullAddress": "13-120/B, Sanjay Nagar, Brindavan Colony, Malkajgiri, 500047, Malkajgiri, Secunderabad, Telangana, 500047",
    "isActive": true,
    "sellerType": "distributor",
    "kyc": {
      "gstin": "36BGGPS8632B1ZB",
      "businessAddress": "13-120/B, Sanjay Nagar, Brindavan Colony, Malkajgiri, 500047, Malkajgiri, Secunderabad, Telangana, 500047",
      "status": "verified",
      "updatedAt": "2026-07-17T00:00:00Z"
    },
    "connectors": {
      "bizom": {
        "status": "not_connected"
      },
      "ondc": {
        "status": "not_connected"
      }
    },
    "permissions": {
      "view": true,
      "write": true,
      "edit": true,
      "update": true
    },
    "managedCompanies": [
      "co-prod-ava-cholayil-health-care-private-limited",
      "co-prod-karnataka-soaps-and-detergents-limited"
    ],
    "companyBrandSelections": [],
    "approvedAt": "2026-07-17T00:00:00Z"
  },
  {
    "id": "seller-prod-rasvitha",
    "name": "MYDHILI KAIPU",
    "email": "prod-9247241176@qwipo.com",
    "phone": "9247241176",
    "businessName": "RASVITHA TRADERS",
    "city": "Secunderabad",
    "pinCode": "500015",
    "state": "Telangana",
    "latitude": 17.4941403,
    "longitude": 78.4907842,
    "fullAddress": "No./Flat No.: 1-6-45/126/3, GROUND FLOOR, YADAMMA NAGAR STREET, Secunderabad, 500015, Alwal, Secunderabad, Telangana, 500015",
    "isActive": true,
    "sellerType": "distributor",
    "kyc": {
      "gstin": "36FLWPK1113C1Z8",
      "businessAddress": "No./Flat No.: 1-6-45/126/3, GROUND FLOOR, YADAMMA NAGAR STREET, Secunderabad, 500015, Alwal, Secunderabad, Telangana, 500015",
      "status": "verified",
      "updatedAt": "2026-07-17T00:00:00Z"
    },
    "connectors": {
      "bizom": {
        "status": "not_connected"
      },
      "ondc": {
        "status": "not_connected"
      }
    },
    "permissions": {
      "view": true,
      "write": true,
      "edit": true,
      "update": true
    },
    "managedCompanies": [
      "co-prod-bambino-agro-industries-ltd",
      "co-prod-gh-industries",
      "co-prod-msr-products",
      "co-prod-rajam-industries-private-limited",
      "co-prod-v-r-enterprises"
    ],
    "companyBrandSelections": [],
    "approvedAt": "2026-07-17T00:00:00Z"
  }
];
