// GENERATED by build-sellers-polygon.cjs — do not edit by hand.
// Production companies (with their tagged brands) linked to the STD 040
// sellers. Adani Wilmar Limited, Gemini Edibles and ITC Limited reuse the
// pre-existing catalog ids co-adani / co-freedom / co-itc.
export const PROD_REPLICA_COMPANIES: {
  id: string;
  name: string;
  brands: { id: string; name: string; imageUrl: string | null }[];
}[] = [
  {
    "id": "co-prod-bambino-agro-industries-ltd",
    "name": "Bambino Agro Industries Ltd",
    "brands": [
      {
        "id": "br-prod-f79765b1",
        "name": "Amore",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/30175dda-3286-41b0-83b1-9481a43cd50d_20260922-190622.png"
      },
      {
        "id": "br-prod-6cb462c3",
        "name": "Bambino",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/886e1652-ac74-43a1-b0dc-cb000f9f5cf2_20260808-101057.jpg"
      },
      {
        "id": "br-prod-1e1d4efb",
        "name": "Nutraawell",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/8b7664e1-3c6c-447e-beb6-ceee4fe05c2d_20260922-190622.png"
      },
      {
        "id": "br-prod-cc431671",
        "name": "Balian",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/a3e4164e-d0b3-4de2-989b-7b7f2be266f1_20260808-101057.jpg"
      }
    ]
  },
  {
    "id": "co-prod-gowdurbar-natural-products-private-limit",
    "name": "Gowdurbar Natural Products Private Limited",
    "brands": [
      {
        "id": "br-prod-bed72c9e",
        "name": "Gowdurbar",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/163bd994-5456-47e8-a675-48bba89b3803_20260922-222623.png"
      }
    ]
  },
  {
    "id": "co-prod-sri-murugan-ghee-store",
    "name": "Sri Murugan Ghee Store",
    "brands": [
      {
        "id": "br-prod-9a952eed",
        "name": "Sri Murugan",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/e6a48dc9-edb6-4f84-8a27-f117dc214afb_20260922-191108.png"
      }
    ]
  },
  {
    "id": "co-prod-swastik-mirch-store",
    "name": "Swastik Mirch Store",
    "brands": [
      {
        "id": "br-prod-e4d739bb",
        "name": "Swastik",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/333b5e76-7fa2-43a9-a40b-3ee25ceae700_20260730-072027.jpg"
      },
      {
        "id": "br-prod-feea960e",
        "name": "Three Mango",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/02e04aef-2095-4d04-8dae-b778b0ed1cc5_20260730-072027.jpg"
      }
    ]
  },
  {
    "id": "co-prod-haw-par-healthcare-limited",
    "name": "Haw Par Healthcare Limited",
    "brands": [
      {
        "id": "br-prod-703afeb1",
        "name": "Tiger Balm",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/7b49fc78-331d-48ef-8ffe-6dc56ae6d395_20260630-175944.png"
      }
    ]
  },
  {
    "id": "co-prod-niaask-oralcare-llp",
    "name": "Niaask OralCare LLP",
    "brands": [
      {
        "id": "br-prod-609a8ef6",
        "name": "Royal",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/4fb7f96e-f0d7-49ee-8f01-767797da6fc4_20260924-170311.jpg"
      }
    ]
  },
  {
    "id": "co-prod-vanesa-care-pvt-ltd",
    "name": "Vanesa Care Pvt. Ltd.",
    "brands": [
      {
        "id": "br-prod-cb96d9b6",
        "name": "Vanesa",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/75b01545-c586-4481-976c-8193ea08a7b8_20260704-155855.png"
      }
    ]
  },
  {
    "id": "co-prod-swastiks-masalas-pickles-and-food-produc",
    "name": "Swastiks Masalas Pickles & Food Products pvt ltd",
    "brands": [
      {
        "id": "br-prod-8b82e5f9",
        "name": "Swastiks",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/0ab60d5c-27d2-4c30-b90f-5c79b0706c6d_20260612-110555.png"
      }
    ]
  },
  {
    "id": "co-prod-vikram-tea-processor-pvt-ltd",
    "name": "Vikram Tea Processor Pvt. Ltd.",
    "brands": [
      {
        "id": "br-prod-49294240",
        "name": "Vikram Tea",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/e8ce5bc3-8969-4bf6-8dc1-f424fe474371_20260826-124156.png"
      }
    ]
  },
  {
    "id": "co-prod-aadishwar-organics-private-limited",
    "name": "Aadishwar Organics Private Limited",
    "brands": [
      {
        "id": "br-prod-23f9306b",
        "name": "Hampi Oil",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/9c4f398c-eaf3-44a6-8f91-57e22fd88ffa_20260630-175600.jpg"
      }
    ]
  },
  {
    "id": "co-prod-adyar-ananda-bhavan-sweets-india-private",
    "name": "Adyar Ananda Bhavan Sweets India Private Limited",
    "brands": [
      {
        "id": "br-prod-f1e1ffa2",
        "name": "A2B",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/7d98a530-cb5a-46fe-b90f-e23f1e1874ef_20260630-145343.jpg"
      }
    ]
  },
  {
    "id": "co-prod-allied-natural-product",
    "name": "Allied Natural Product",
    "brands": [
      {
        "id": "br-prod-64d4dac6",
        "name": "Vivi",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/f6702090-7b93-4440-b262-84442b7bb78b_20260630-145900.png"
      }
    ]
  },
  {
    "id": "co-prod-ambica-agarbathies-aroma-and-industries-",
    "name": "Ambica Agarbathies Aroma & Industries Limited",
    "brands": [
      {
        "id": "br-prod-13206a6d",
        "name": "Ambica",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/62d08eb3-ed66-40cf-a04c-2d67df96ae55_20260630-150055.jpg"
      }
    ]
  },
  {
    "id": "co-prod-aswini-homeo-and-ayurvedic-products-pvt-",
    "name": "Aswini Homeo & Ayurvedic Products Pvt. Ltd.",
    "brands": [
      {
        "id": "br-prod-5e28071b",
        "name": "Aswini",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/4a1c3e82-c8d3-4c20-b8a6-c45ae402ad60_20260630-150340.jpg"
      }
    ]
  },
  {
    "id": "co-prod-buy-happy-marketing-llp",
    "name": "Buy Happy Marketing Llp",
    "brands": [
      {
        "id": "br-prod-9583a11f",
        "name": "Vip",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/ab16a655-ca02-45e5-b036-c5aa8f5a1bfc_20260630-150622.jpg"
      }
    ]
  },
  {
    "id": "co-prod-dey-s-medical-stores-pvt-ltd",
    "name": "Dey'S Medical Stores Pvt. Ltd",
    "brands": [
      {
        "id": "br-prod-7805485e",
        "name": "Keo Karpin",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/15a6bfcb-ffba-4d4a-b4d8-a301c97fb5ea_20260630-151126.jpg"
      }
    ]
  },
  {
    "id": "co-prod-duracell-inc",
    "name": "Duracell Inc.",
    "brands": [
      {
        "id": "br-prod-3f90ff2a",
        "name": "Duracell",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/0dfdb872-0fa3-4272-8c8f-d495ddddb779_20260630-151453.jpg"
      }
    ]
  },
  {
    "id": "co-prod-dwibhashi-bapanna-ayurveda-nilayam-pvt-l",
    "name": "Dwibhashi Bapanna Ayurveda Nilayam Pvt. Ltd.",
    "brands": [
      {
        "id": "br-prod-e8b25cb1",
        "name": "Dwibhashi Ayurvedic",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/77298149-79ee-49a7-90ee-5c26b5f0e57d_20260531-225217.png"
      }
    ]
  },
  {
    "id": "co-prod-harvesta-farming-private-limited",
    "name": "Harvesta Farming Private Limited",
    "brands": [
      {
        "id": "br-prod-04e1f805",
        "name": "Farmer First",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/abb08b37-c31a-4d3a-a87e-421a45d5212c_20260630-152627.png"
      }
    ]
  },
  {
    "id": "co-prod-hygienic-research-institute-private-limi",
    "name": "Hygienic Research Institute Private Limited",
    "brands": [
      {
        "id": "br-prod-02b7d5af",
        "name": "Super Vasmol",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/21be119e-18e1-46e7-a5d0-5cd801ace0ba_20260630-153706.jpg"
      }
    ]
  },
  {
    "id": "co-prod-laljee-godhoo-and-co",
    "name": "Laljee Godhoo & Co.",
    "brands": [
      {
        "id": "br-prod-61a1534e",
        "name": "LG Hing",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/e17118be-1411-4a38-9c00-754915a93ca5_20260630-153851.jpg"
      }
    ]
  },
  {
    "id": "co-prod-mayuri-chemicals-private-limited",
    "name": "Mayuri Chemicals Private Limited",
    "brands": [
      {
        "id": "br-prod-f78a6ab1",
        "name": "Mayuri",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/8f9c60f2-3b3c-4235-a522-35daf7cf2576_20260630-154431.jpg"
      }
    ]
  },
  {
    "id": "co-prod-midas-hygiene-industries-pvt-ltd",
    "name": "Midas Hygiene Industries Pvt. Ltd",
    "brands": [
      {
        "id": "br-prod-d68b9528",
        "name": "Laxmanarekha",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/f1d32d0b-55e6-4f0e-9025-478d7044f42d_20260630-154650.jpg"
      }
    ]
  },
  {
    "id": "co-prod-nextg-apex-india-pvt-ltd",
    "name": "Nextg Apex India Pvt. Ltd.",
    "brands": [
      {
        "id": "br-prod-9d92f1aa",
        "name": "Kravour",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/4a2518b3-0d17-48c9-bf35-fc95460c0cc9_20260630-161024.jpg"
      },
      {
        "id": "br-prod-e54b66fd",
        "name": "Mamafeast",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/bc48c6e6-da5f-461d-8dcb-0d12abb9b82b_20260630-161024.jpg"
      },
      {
        "id": "br-prod-130ba9a2",
        "name": "Sinfull",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/a53ed3fa-a0c0-45e5-9087-ebbfae25f703_20260630-161024.jpg"
      },
      {
        "id": "br-prod-09cd2d69",
        "name": "Sip Crush",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/e987bf23-dbff-41d6-8e61-b6a79b50baf0_20260630-161024.jpg"
      }
    ]
  },
  {
    "id": "co-prod-sachin-traders",
    "name": "Sachin Traders",
    "brands": [
      {
        "id": "br-prod-2c01d8a3",
        "name": "Subhamastu",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/11c552d1-1421-4c73-913d-d222f32b9248_20260630-163754.jpg"
      }
    ]
  },
  {
    "id": "co-prod-sesa-care-pvt-ltd",
    "name": "Sesa Care Pvt. Ltd.",
    "brands": [
      {
        "id": "br-prod-c7db34fe",
        "name": "Sesa Care",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/4d9ef6fc-e060-4fef-98a1-126f82bd8706_20260630-164041.jpg"
      }
    ]
  },
  {
    "id": "co-prod-the-national-tea-depot",
    "name": "The National Tea Depot.",
    "brands": [
      {
        "id": "br-prod-c1263adb",
        "name": "Hyvita Tea",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/3eedd6be-9d00-48f6-9afd-4d3225ffe412_20260630-164504.jpg"
      }
    ]
  },
  {
    "id": "co-prod-vicco-laboratories",
    "name": "Vicco Laboratories",
    "brands": [
      {
        "id": "br-prod-e2257ccb",
        "name": "Vicco",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/71fa09c7-afa7-4cc5-8db7-48998172d540_20260531-233336.png"
      }
    ]
  },
  {
    "id": "co-prod-vijaya-chemicals-and-toilet-works-telang",
    "name": "Vijaya Chemicals & Toilet Works Telangana",
    "brands": [
      {
        "id": "br-prod-7ab4134d",
        "name": "Ashoka",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/3de44494-6347-4628-acc2-7f1c344335f0_20260630-174219.png"
      }
    ]
  },
  {
    "id": "co-prod-emami-limited",
    "name": "Emami Limited",
    "brands": [
      {
        "id": "br-prod-2455310a",
        "name": "7 Oils in One",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/b3d98f02-8569-4c3f-9a12-86a182131bcb_20260806-123207.png"
      },
      {
        "id": "br-prod-9db138ba",
        "name": "BoroPlus",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/ae70b0ac-720a-457c-ac1c-bb1043e114fe_20260727-124643.png"
      },
      {
        "id": "br-prod-2a4e297d",
        "name": "DermiCool",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/271e7b76-35cc-4e16-8dba-88a567feef4b_20260727-124643.png"
      },
      {
        "id": "br-prod-1356e27c",
        "name": "Kesh King",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/0e80187e-6fcc-4ca7-9fc0-efa439416de2_20260727-124643.png"
      },
      {
        "id": "br-prod-7c658d56",
        "name": "Mentho Plus",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/15a82b0b-f406-4163-bb97-cee31f049ea1_20260727-124643.png"
      },
      {
        "id": "br-prod-34de6d7d",
        "name": "Navratna",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/479a587f-a13a-47a2-91b4-7c60e2c06931_20260727-124643.png"
      },
      {
        "id": "br-prod-15439dd5",
        "name": "Smart And Handsome",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/82ee8eae-8f8d-43ca-ae30-f91a27c6e955_20260727-124643.png"
      },
      {
        "id": "br-prod-438488de",
        "name": "Zandu",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/6edfec7d-584f-403e-8491-a8a610b2964b_20260727-124643.png"
      }
    ]
  },
  {
    "id": "co-prod-aachi-masala-foods-private-limited",
    "name": "Aachi Masala Foods Private Limited",
    "brands": [
      {
        "id": "br-prod-edc3d6ac",
        "name": "Aachi",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/18892ab2-98c0-4283-aacb-960165d374f7_20260909-144150.jpg"
      },
      {
        "id": "br-prod-da6a08fc",
        "name": "Sabash",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/a071ff01-939b-4774-9254-a0a89b767203_20260910-001704.png"
      },
      {
        "id": "br-prod-52ffb55b",
        "name": "Twinkle",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/9cfebef3-e68b-4e22-aadb-794577efc3b6_20260910-001704.png"
      }
    ]
  },
  {
    "id": "co-prod-jntl-consumer-health-india-private-limit",
    "name": "JNTL Consumer Health (India) Private Limited",
    "brands": [
      {
        "id": "br-prod-dbe80baf",
        "name": "Aveeno",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/2a8156bd-b957-4890-af0b-f752a72e0ecd_20260921-223706.png"
      },
      {
        "id": "br-prod-34540b66",
        "name": "Benadryl",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/bfc9cd5e-cb5c-42c8-947e-48b1e93a288b_20260921-223706.jpg"
      },
      {
        "id": "br-prod-f5d8309f",
        "name": "Carefree",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/abd95c77-740e-48e5-8708-328da71bdc78_20260921-223706.png"
      },
      {
        "id": "br-prod-6cd156ec",
        "name": "Clean & Clear",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/74dde967-355c-48af-9fea-3ead6f60f811_20260921-223706.png"
      },
      {
        "id": "br-prod-22775371",
        "name": "Erzl",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/b0a4c2df-d395-48ef-b959-7bfc04286e20_20260921-223706.jpg"
      },
      {
        "id": "br-prod-022b7559",
        "name": "Johnson's",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/114ea7ad-602f-4a04-8750-2cbe92a9b246_20260921-223706.png"
      },
      {
        "id": "br-prod-27b88b03",
        "name": "Listerine",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/509cb08d-e3b2-45dd-a31b-7812be14f16a_20260921-223706.png"
      },
      {
        "id": "br-prod-30550b45",
        "name": "Neutrogena",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/44d510eb-9c51-4576-a5b6-ce0b24b3e3aa_20260921-223706.png"
      },
      {
        "id": "br-prod-3ace15bf",
        "name": "Ors",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/90c78986-c3aa-43c9-8c69-496b7502f541_20260922-173251.png"
      },
      {
        "id": "br-prod-398659d3",
        "name": "Orsl",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/daee1c22-b9cc-46b1-be6f-647ff3a67fa4_20260922-172805.jpg"
      },
      {
        "id": "br-prod-e578dc41",
        "name": "Stayfree",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/6080c78d-50eb-450c-97c7-d74a68147b39_20260921-223706.png"
      }
    ]
  },
  {
    "id": "co-prod-colgate-palmolive",
    "name": "Colgate-Palmolive",
    "brands": [
      {
        "id": "br-prod-2fabc7a5",
        "name": "Colgate",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/5f2c5bbc-186d-4767-8b32-b81749803460_20260714-165113.jpg"
      }
    ]
  },
  {
    "id": "co-prod-3f-industries-ltd",
    "name": "3f Industries Ltd",
    "brands": [
      {
        "id": "br-prod-4977a0fc",
        "name": "Palm Delite",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/5be5d5cd-985c-4c0d-86e7-ac09c3e3ab00_20260705-160336.jpg"
      }
    ]
  },
  {
    "id": "co-prod-emami-agrotech-limited",
    "name": "Emami Agrotech Limited",
    "brands": [
      {
        "id": "br-prod-e3de64f3",
        "name": "Best Choice",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/58c47851-deb4-4325-a8f8-3624c71e94be_20260705-160130.jpg"
      }
    ]
  },
  {
    "id": "co-prod-fourtune-agri-solutions",
    "name": "Fourtune Agri Solutions",
    "brands": [
      {
        "id": "br-prod-a8474887",
        "name": "Poshak",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/283de373-dc49-4a20-ae2e-047a925a4636_20260923-161143.jpg"
      }
    ]
  },
  {
    "id": "co-prod-healthy-heart-foods",
    "name": "Healthy Heart Foods",
    "brands": [
      {
        "id": "br-prod-f35c29d3",
        "name": "Healthy Heart",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/9d037455-89c1-43ce-8f2f-1fce89f7ffc1_20260705-154824.jpg"
      }
    ]
  },
  {
    "id": "co-prod-kedia-agro",
    "name": "Kedia Agro",
    "brands": [
      {
        "id": "br-prod-26e3b738",
        "name": "Festival Oil",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/fee73cd7-f711-4458-adc6-2b7a994660b9_20260531-234932.png"
      },
      {
        "id": "br-prod-f1061623",
        "name": "Goldfresh",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/43d610d2-3592-4263-b92f-27b2f91ba678_20260606-222812.png"
      }
    ]
  },
  {
    "id": "co-prod-magnum-enterprises",
    "name": "Magnum Enterprises",
    "brands": [
      {
        "id": "br-prod-2ef2fad4",
        "name": "Sunsurre Oil",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/539f079b-7b7e-4e4b-a91c-42d4a59f4515_20260606-224505.png"
      }
    ]
  },
  {
    "id": "co-prod-navabhart-limited",
    "name": "Navabhart Limited",
    "brands": [
      {
        "id": "br-prod-0f901a4a",
        "name": "Supermathi",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/5971ecc5-f8e3-4bbd-a571-bf57a284fade_20260705-161557.jpg"
      }
    ]
  },
  {
    "id": "co-prod-patanjali-foods-limited",
    "name": "Patanjali Foods Limited",
    "brands": [
      {
        "id": "br-prod-603653eb",
        "name": "Sunrich",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/ff8f66b8-4872-49cc-9c80-5164dbd43b4b_20260705-160901.jpg"
      },
      {
        "id": "br-prod-2a4e7665",
        "name": "Nutrela",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/327d7de0-fb46-46cc-aa42-5a1ad7ac754f_20260916-130126.png"
      },
      {
        "id": "br-prod-03618acb",
        "name": "Patanjali",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/6df7bef5-0f90-4611-8274-af695fe75c3b_20260916-130126.png"
      }
    ]
  },
  {
    "id": "co-prod-pattabi-agro-foods-pvt-ltd",
    "name": "Pattabi agro foods Pvt Ltd",
    "brands": [
      {
        "id": "br-prod-7f31283e",
        "name": "Sri Lohitha",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/41b5e103-d2dc-4937-bc03-9b1f6503f928_20260705-162101.jpg"
      }
    ]
  },
  {
    "id": "co-prod-santhoshimatha-edible-oils-refinery-pvt-",
    "name": "Santhoshimatha Edible Oils Refinery Pvt. Ltd",
    "brands": [
      {
        "id": "br-prod-3a2f61e4",
        "name": "Priya Gold",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/ca3e4ee5-f70a-4a8f-8d15-d4a03bb96052_20260531-235227.png"
      }
    ]
  },
  {
    "id": "co-prod-shree-gajanan-industries",
    "name": "Shree Gajanan Industries",
    "brands": [
      {
        "id": "br-prod-1993f696",
        "name": "Gajanan",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/9431b8d2-5099-4f2d-9452-3f6157df5ddc_20260704-110718.jpg"
      }
    ]
  },
  {
    "id": "co-prod-sri-tulasi-industries",
    "name": "Sri Tulasi Industries",
    "brands": [
      {
        "id": "br-prod-56607779",
        "name": "Heartiva",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/c7853cce-063d-44e1-802f-a71431bcb57d_20260705-155723.png"
      },
      {
        "id": "br-prod-5830c0f3",
        "name": "Tasty Gold",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/b68a1a3b-c7c6-4a02-882d-8f5bf19e2dd4_20260705-155723.jpg"
      },
      {
        "id": "br-prod-b288ea19",
        "name": "Tulasi",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/db924e4b-ad2d-4ea3-861f-a475fece5279_20260705-155723.jpg"
      }
    ]
  },
  {
    "id": "co-prod-grb-dairy-foods-pvt-ltd",
    "name": "GRB DAIRY FOODS PVT.LTD.",
    "brands": [
      {
        "id": "br-prod-8005df35",
        "name": "GRB",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/abeed291-d764-45de-a8f6-4f55618e9941_20260530-181955.png"
      }
    ]
  },
  {
    "id": "co-prod-raghav-lifestyle-products",
    "name": "Raghav Lifestyle Products",
    "brands": [
      {
        "id": "br-prod-5b75a2ee",
        "name": "Ajay",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/c4f8615c-105b-4721-b286-c1fbce78c0de_20260530-181903.png"
      }
    ]
  },
  {
    "id": "co-prod-ullas-agarbathi",
    "name": "Ullas Agarbathi",
    "brands": [
      {
        "id": "br-prod-4b09893f",
        "name": "Ullas",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/6681a640-c2e0-421d-ada3-133d4c5a62ed_20260731-193705.jpg"
      }
    ]
  },
  {
    "id": "co-prod-ambati-subbanna-and-co",
    "name": "Ambati Subbanna & Co",
    "brands": [
      {
        "id": "br-prod-0477ffbd",
        "name": "A S Brand",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/a88faceb-7bfa-4970-ad1a-aeaa52a2ecd9_20260603-171039.png"
      }
    ]
  },
  {
    "id": "co-prod-jyothy-labs-limited",
    "name": "Jyothy Labs Limited",
    "brands": [
      {
        "id": "br-prod-1b705e36",
        "name": "Exo",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/d2b63318-f530-4cb8-8231-8e8f06c2e43f_20260926-173045.png"
      },
      {
        "id": "br-prod-4ce57bf4",
        "name": "Henko",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/22f629e5-5934-4d0b-96b2-8e046ea45a2e_20260926-173045.png"
      },
      {
        "id": "br-prod-41db8aa7",
        "name": "Margo",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/4892d12b-b675-446c-9aa1-202db3e3b576_20260921-180752.jpg"
      },
      {
        "id": "br-prod-99ab4bea",
        "name": "Maxo",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/8643ef68-7e6c-41ed-9671-4ab510433a89_20260926-173045.png"
      },
      {
        "id": "br-prod-0b0a72db",
        "name": "Maya",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/4e415da4-2e1e-4cf6-a353-242d978b8ccc_20260926-173045.png"
      },
      {
        "id": "br-prod-3985aeee",
        "name": "More Light",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/a32e5278-8483-4f78-bd74-c2c65d06221e_20260926-173045.png"
      },
      {
        "id": "br-prod-dd263d69",
        "name": "Mr White",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/a23c4f37-f4fa-429f-9693-4db254484580_20260926-173045.png"
      },
      {
        "id": "br-prod-ddaa9ad1",
        "name": "Neem Active",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/53cd4cff-e0f9-44d0-a283-b5e8a705a8d9_20260926-173045.png"
      },
      {
        "id": "br-prod-d7ee5868",
        "name": "T-Shine",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/c7637699-6773-4195-9a52-7fc49040778f_20260926-173045.png"
      },
      {
        "id": "br-prod-0658eefe",
        "name": "Ujala",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/3581a3b7-e15b-48e3-a2ab-3cc6797e18be_20260926-173045.png"
      }
    ]
  },
  {
    "id": "co-prod-kirti-oil-industries-private-limited",
    "name": "KIRTI oil industries private limited",
    "brands": [
      {
        "id": "br-prod-005e4a14",
        "name": "Kirti",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/dc380fa5-e4fa-4dd7-bc1d-d573163cb37e_20260726-003840.png"
      }
    ]
  },
  {
    "id": "co-prod-e-i-d-parry-india-ltd",
    "name": "E I D Parry India Ltd",
    "brands": [
      {
        "id": "br-prod-1f02644d",
        "name": "Parry",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/5908b662-3ab2-4d45-92cd-82d33eddde27_20260531-235918.png"
      }
    ]
  },
  {
    "id": "co-prod-langer-masala",
    "name": "Langer Masala",
    "brands": [
      {
        "id": "br-prod-ddd4fd83",
        "name": "Langer",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/8d89a6e3-8cc7-4424-957e-5a2a096a9ba5_20260921-205445.png"
      }
    ]
  },
  {
    "id": "co-prod-sky-enterprise-private-limited",
    "name": "SKY Enterprise Private Limited",
    "brands": [
      {
        "id": "br-prod-f20a02ee",
        "name": "Starzing",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/766746b6-d3a3-49a4-b3d4-994dec40255e_20260921-205018.jpg"
      }
    ]
  },
  {
    "id": "co-prod-ushodaya-enterprises-private-limited",
    "name": "Ushodaya Enterprises Private Limited",
    "brands": [
      {
        "id": "br-prod-398f0900",
        "name": "Priya",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/a40270dd-88bb-47ba-9762-4b9db51cadb7_20260530-182042.png"
      }
    ]
  },
  {
    "id": "co-prod-ava-cholayil-health-care-private-limited",
    "name": "AVA Cholayil Health Care Private Limited",
    "brands": [
      {
        "id": "br-prod-99e8d63a",
        "name": "Medimix",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/0e1a5100-c308-4747-8fdc-79f816445a16_20260806-214712.png"
      }
    ]
  },
  {
    "id": "co-prod-karnataka-soaps-and-detergents-limited",
    "name": "Karnataka Soaps And Detergents Limited",
    "brands": [
      {
        "id": "br-prod-b70a9a9a",
        "name": "Mysore Sandal",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/2da2fa9d-9d67-4d47-8424-e7dde2f53f8c_20260530-182320.png"
      }
    ]
  },
  {
    "id": "co-prod-international-flavours-and-fragrances-in",
    "name": "International Flavours & Fragrances India Private Limited.",
    "brands": [
      {
        "id": "br-prod-71d84635",
        "name": "IFF",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/898c324f-7c06-4385-8394-1558787c2015_20260708-094515.png"
      }
    ]
  },
  {
    "id": "co-prod-lion-dates-impex-p-ltd",
    "name": "Lion Dates Impex (P) Ltd",
    "brands": [
      {
        "id": "br-prod-4868ace6",
        "name": "Lion",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/71596d00-9d01-459e-926c-9ec511e6f218_20260611-160727.png"
      }
    ]
  },
  {
    "id": "co-prod-msk-flavours",
    "name": "Msk Flavours.",
    "brands": [
      {
        "id": "br-prod-4fb33f94",
        "name": "Sanghi",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/0ecd4031-f06c-4952-ae38-fb0bbd01c33a_20260708-093956.png"
      }
    ]
  },
  {
    "id": "co-prod-peppergami-food-labs-private-limited",
    "name": "PEPPERGAMI FOOD LABS PRIVATE LIMITED.",
    "brands": [
      {
        "id": "br-prod-ac3fe7b3",
        "name": "Mas Foods",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/1963d40d-3b70-4169-b2fa-12939eb89175_20260708-095025.png"
      }
    ]
  },
  {
    "id": "co-prod-sgr-777-foods-private-limited",
    "name": "SGR (777) Foods Private Limited.",
    "brands": [
      {
        "id": "br-prod-63b4f668",
        "name": "SGR (777)",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/bf72195c-9472-4df5-b7f5-5070282b3715_20260708-093221.png"
      }
    ]
  },
  {
    "id": "co-prod-weikfield-foods-private-limited",
    "name": "Weikfield Foods Private Limited.",
    "brands": [
      {
        "id": "br-prod-b5c9206f",
        "name": "Weikfield",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/9cb5f36f-ae30-4927-b91a-f2877ff79513_20260708-095621.png"
      }
    ]
  },
  {
    "id": "co-prod-radiant-indus-chem-pvt-ltd",
    "name": "Radiant Indus Chem Pvt Ltd",
    "brands": [
      {
        "id": "br-prod-bb45d019",
        "name": "Mealtime",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/2ae18ae9-0821-46c3-98f0-1ec1cefa5428_20260908-112527.jpg"
      },
      {
        "id": "br-prod-832edb50",
        "name": "Mrs Food rite",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/d8a53d52-70b8-41d1-8e5b-cf8de923e481_20260908-112527.png"
      }
    ]
  },
  {
    "id": "co-prod-darshan-international",
    "name": "Darshan International",
    "brands": [
      {
        "id": "br-prod-0b24a861",
        "name": "Darshan",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/ab02ad51-4e53-46cc-af49-d3941b78a2e1_20260918-110847.png"
      }
    ]
  },
  {
    "id": "co-prod-gt-products",
    "name": "GT Products",
    "brands": [
      {
        "id": "br-prod-be5d2013",
        "name": "Two Hands",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/f67b1471-6f95-4060-b554-00951fe5542e_20260918-110958.png"
      }
    ]
  },
  {
    "id": "co-prod-sri-vijayalakshmi-agarbathi-works",
    "name": "Sri Vijayalakshmi Agarbathi Works",
    "brands": [
      {
        "id": "br-prod-1598377b",
        "name": "Liberty Agarbathi",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/8d74e7a3-0f6a-40f6-8d4c-85a97313d81f_20260917-234823.png"
      }
    ]
  },
  {
    "id": "co-prod-marino-food-products-pvt-ltd",
    "name": "Marino Food Products Pvt Ltd",
    "brands": [
      {
        "id": "br-prod-b9ff2a22",
        "name": "Marino",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/d7191a89-c693-4bb3-8242-175aba0f20a9_20260630-173920.png"
      }
    ]
  },
  {
    "id": "co-prod-sln-coffee-pvt-ltd",
    "name": "SLN Coffee Pvt. Ltd",
    "brands": [
      {
        "id": "br-prod-8152f5c6",
        "name": "Levista",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/f6560885-e242-4883-aa38-2e3ffe52c64d_20260630-173646.png"
      }
    ]
  },
  {
    "id": "co-prod-lohiya-edible-oils-pvt-ltd",
    "name": "Lohiya Edible Oils Pvt Ltd",
    "brands": [
      {
        "id": "br-prod-9f7e386e",
        "name": "Gold Drop",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/dde03af5-b71a-4e55-b757-74f13216eb5b_20260606-221032.png"
      }
    ]
  },
  {
    "id": "co-prod-patanjali-ayurved-limited",
    "name": "Patanjali Ayurved Limited",
    "brands": [
      {
        "id": "br-prod-24ad71b6",
        "name": "Ruchi Gold",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/5de14f10-9032-45cb-a67c-9241cd1b1841_20260531-233639.png"
      }
    ]
  },
  {
    "id": "co-prod-shree-saraiwwalaa-aggrr-refineries-limit",
    "name": "Shree Saraiwwalaa Aggrr Refineries Limited",
    "brands": [
      {
        "id": "br-prod-4bd81c05",
        "name": "Naturralle",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/0eee5b5c-1b82-4311-bff9-ae89c2a5726a_20260601-002243.png"
      }
    ]
  },
  {
    "id": "co-prod-sri-sainath-agro-oils",
    "name": "Sri Sainath Agro Oils",
    "brands": [
      {
        "id": "br-prod-bb4da4d9",
        "name": "Mahalaxmi",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/adc1eb38-cb11-43c0-b7a5-2bcc6ea154cf_20260814-233410.jpg"
      }
    ]
  },
  {
    "id": "co-prod-telangana-cooperative-oilseeds-growers-f",
    "name": "Telangana Cooperative Oilseeds Growers Federation Ltd",
    "brands": [
      {
        "id": "br-prod-c0c69a58",
        "name": "Vijaya",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/17128fef-4393-457d-a597-27962d854b2c_20260601-003208.png"
      }
    ]
  },
  {
    "id": "co-prod-elite-foods-pvt-ltd",
    "name": "Elite Foods PVT. LTD",
    "brands": [
      {
        "id": "br-prod-faabf115",
        "name": "Elite",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/82b9d44b-85b0-4597-aa8f-72c6dca51adc_20260916-162318.png"
      }
    ]
  },
  {
    "id": "co-prod-karkhana-zinda-tilismath-llp",
    "name": "Karkhana Zinda Tilismath LLP",
    "brands": [
      {
        "id": "br-prod-99e5b298",
        "name": "Zinda",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/1d805b56-888f-4fc2-b844-78c70b24511a_20260530-182233.png"
      }
    ]
  },
  {
    "id": "co-prod-orkla-india-private-limited",
    "name": "Orkla India Private Limited",
    "brands": [
      {
        "id": "br-prod-0efd356b",
        "name": "Eastern",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/48a05767-de6a-4bd5-bff6-01d57c143638_20260530-182522.png"
      },
      {
        "id": "br-prod-e96161c0",
        "name": "MTR",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/aa2de32c-ba0f-4666-a825-b4d0fae00f52_20260530-182522.png"
      }
    ]
  },
  {
    "id": "co-prod-garuda-polyflex-foods-private-limited",
    "name": "Garuda Polyflex Foods Private Limited",
    "brands": [
      {
        "id": "br-prod-2866036d",
        "name": "Gon Mad",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/d619d37a-5b62-4921-99a8-1b5813d0d80f_20260905-120245.jpg"
      }
    ]
  },
  {
    "id": "co-prod-siva-shakthi-soap-works",
    "name": "Siva Shakthi Soap Works",
    "brands": [
      {
        "id": "br-prod-27267ed7",
        "name": "Micron",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/3e04b4c6-c1cc-43f4-8e64-bfe5f90b9bb0_20260905-120046.jpg"
      }
    ]
  },
  {
    "id": "co-prod-jhaveri-industries",
    "name": "Jhaveri Industries",
    "brands": [
      {
        "id": "br-prod-2b279e8a",
        "name": "Badshah",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/f32113df-28c3-4590-8f65-c208c3b3f3fb_20260819-095152.jpg"
      }
    ]
  },
  {
    "id": "co-prod-gh-industries",
    "name": "GH Industries",
    "brands": [
      {
        "id": "br-prod-cba2965a",
        "name": "Harathi",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/8bd5c183-5ba0-4b9c-ac93-e98f917f1d71_20260808-103721.png"
      }
    ]
  },
  {
    "id": "co-prod-msr-products",
    "name": "MSR Products",
    "brands": [
      {
        "id": "br-prod-c57986a2",
        "name": "Today 365",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/c8a3d1c2-a27a-499b-8f44-9006fed735e1_20260808-100700.png"
      }
    ]
  },
  {
    "id": "co-prod-rajam-industries-private-limited",
    "name": "Rajam Industries Private Limited",
    "brands": [
      {
        "id": "br-prod-d31a9f86",
        "name": "Oorvasi",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/20ca3c46-28eb-4852-98ca-81c0f43f4b47_20260808-095738.png"
      }
    ]
  },
  {
    "id": "co-prod-v-r-enterprises",
    "name": "V R Enterprises",
    "brands": [
      {
        "id": "br-prod-642fc857",
        "name": "Shiva",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/66158793-6ece-48bb-a33a-765f3bc8d1a5_20260808-104242.jpg"
      }
    ]
  },
  {
    "id": "co-prod-sri-gantasala-foods",
    "name": "Sri Gantasala Foods",
    "brands": [
      {
        "id": "br-prod-22ac758e",
        "name": "Gantasala Foods",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/ade39dcd-aeb0-4e95-9ac4-3adcc7aa2426_20260611-161438.png"
      }
    ]
  },
  {
    "id": "co-prod-henna-industries-pvt-ltd",
    "name": "Henna Industries Pvt Ltd.",
    "brands": [
      {
        "id": "br-prod-b5016296",
        "name": "Black Rose",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/37e8dfc9-7df4-4ba6-a969-99faf51b9d9e_20260531-231918.png"
      },
      {
        "id": "br-prod-378fede3",
        "name": "Color Mate",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/d8d6ce30-fe55-4034-8314-b24faefab853_20260727-214257.png"
      }
    ]
  },
  {
    "id": "co-prod-dharampal-satyapal-group",
    "name": "Dharampal Satyapal Group",
    "brands": [
      {
        "id": "br-prod-bf2eb509",
        "name": "Pulse",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/5df917e2-c55c-4aea-992b-148e3130a385_20260831-171942.jpg"
      }
    ]
  },
  {
    "id": "co-prod-haldiram-snacks-food-private-limited",
    "name": "Haldiram Snacks Food Private Limited",
    "brands": [
      {
        "id": "br-prod-6ffbe9fd",
        "name": "Haldirams",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/9fe62201-2edc-4aa9-b856-405b85591c39_20260901-091628.jpg"
      }
    ]
  },
  {
    "id": "co-prod-hell-energy-magyarorsz-g-kft",
    "name": "Hell Energy Magyarország Kft.",
    "brands": [
      {
        "id": "br-prod-68db34f4",
        "name": "Hell",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/52a94218-0e46-4037-a47e-20fe5c225e5d_20260805-150527.png"
      }
    ]
  },
  {
    "id": "co-prod-lotte-india-corporation-private-limited",
    "name": "Lotte India Corporation Private Limited",
    "brands": [
      {
        "id": "br-prod-42aacaac",
        "name": "Lotte",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/15701ea3-af94-4b20-be71-6d46460802a6_20260909-190457.png"
      }
    ]
  },
  {
    "id": "co-prod-wonderworks-private-ltd",
    "name": "WonderWorks Private Ltd",
    "brands": [
      {
        "id": "br-prod-236af1ac",
        "name": "Ziggy",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/7e583800-30ce-4ffe-9f93-036688336008_20260904-151502.jpg"
      }
    ]
  },
  {
    "id": "co-prod-ferrero-group",
    "name": "Ferrero Group",
    "brands": [
      {
        "id": "br-prod-892989c5",
        "name": "Kinder",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/e3b4c2e5-1185-44df-af89-a09ce96140d6_20260915-095447.png"
      },
      {
        "id": "br-prod-ba087398",
        "name": "Nutella",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/e51b16bf-a1b5-4acd-b8fd-5a06825337f1_20260915-095447.png"
      },
      {
        "id": "br-prod-b076e853",
        "name": "Tic Tac",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/58bd3a99-be2e-4449-9946-962b942bf380_20260915-095447.png"
      }
    ]
  },
  {
    "id": "co-prod-bajaj-consumer-care-limited",
    "name": "Bajaj Consumer Care Limited",
    "brands": [
      {
        "id": "br-prod-ae6cbde9",
        "name": "Bajaj",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/9d82c169-4dbb-4498-9833-3c3eb19a9205_20260905-100631.png"
      },
      {
        "id": "br-prod-173ae181",
        "name": "Banjaras",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/ecb862e4-b41e-4f58-bdfe-276d4e515d5f_20260923-170454.jpg"
      }
    ]
  },
  {
    "id": "co-prod-balaji-trading",
    "name": "Balaji Trading",
    "brands": [
      {
        "id": "br-prod-0d536e7e",
        "name": "A1 Basmati",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/98a56ae6-cadc-451e-81e6-f15d527abe3c_20260923-143621.jpg"
      }
    ]
  },
  {
    "id": "co-prod-sri-sankar-dalla-and-general-merchants",
    "name": "Sri Sankar Dalla & General Merchants",
    "brands": [
      {
        "id": "br-prod-64812e99",
        "name": "Sri Trisul",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/e7c41b94-a76d-49f9-83c0-07a8157599a3_20260921-223133.png"
      }
    ]
  },
  {
    "id": "co-prod-srivari-spices-and-foods-limited",
    "name": "Srivari Spices and Foods Limited",
    "brands": [
      {
        "id": "br-prod-0fb0df55",
        "name": "Srivari",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/1e1a8dac-941f-462c-a13e-eb51dbfc2d09_20260921-203319.jpg"
      }
    ]
  },
  {
    "id": "co-prod-tata-consumer-products-limited",
    "name": "Tata Consumer Products Limited",
    "brands": [
      {
        "id": "br-prod-c8d6a2ae",
        "name": "Tata",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/4da5e888-6670-4f1c-95fe-d3e6cf309e9a_20260601-003139.png"
      },
      {
        "id": "br-prod-e03ceff6",
        "name": "Chings Secret",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/cd823970-093f-4265-b1dd-e93b933c8cbb_20260918-155207.png"
      },
      {
        "id": "br-prod-8f5f757d",
        "name": "Organic India",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/9803a411-862e-4256-aedc-c3f1975a5f3e_20260818-135641.jpg"
      },
      {
        "id": "br-prod-4bd4fc29",
        "name": "Smith and Jones",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/e9055e7b-ba24-45aa-b5e5-e25dec81d567_20260918-155207.png"
      },
      {
        "id": "br-prod-88e8c01a",
        "name": "Soulfull",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/204f83fe-a418-4f0e-8ed0-371a4da2c36a_20260918-155207.png"
      },
      {
        "id": "br-prod-daddc5b0",
        "name": "Tata Agni",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/24627422-1b0f-4743-a5a2-312d1e0b915a_20260818-134531.jpg"
      },
      {
        "id": "br-prod-039d3df1",
        "name": "Tata Coffee",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/592e8eac-1425-4177-99a6-d8b96b1bd45c_20260918-155207.png"
      },
      {
        "id": "br-prod-d5ae280d",
        "name": "Tata Sampann",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/ae7c8d78-69d2-46fc-ae7e-aeef7506abfb_20260918-155207.png"
      },
      {
        "id": "br-prod-0cb1ec01",
        "name": "Tata Simply Better",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/02377fe9-c9c5-4811-abba-e6a922480e3e_20260918-155207.png"
      },
      {
        "id": "br-prod-980c49da",
        "name": "Tata Tea",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/da23f46a-e0b1-4cfb-b52c-e2d40e535164_20260918-153640.png"
      },
      {
        "id": "br-prod-e725cf8a",
        "name": "Tetley",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/54d09b55-a100-4388-afc7-7ab755d7ee5c_20260818-134531.png"
      }
    ]
  },
  {
    "id": "co-prod-godrej-agrovet-limited",
    "name": "Godrej Agrovet Limited",
    "brands": [
      {
        "id": "br-prod-d5e3681b",
        "name": "Jersey",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/a99b451f-e382-48c2-81f0-9e243d6bd362_20260922-142829.png"
      }
    ]
  },
  {
    "id": "co-prod-anmol-industries-limited",
    "name": "Anmol Industries Limited",
    "brands": [
      {
        "id": "br-prod-4bdfd7c8",
        "name": "Anmol",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/1eadef64-a9a3-45de-9b68-f7af6a4b00bd_20260818-142912.png"
      }
    ]
  },
  {
    "id": "co-prod-balaji-wafers-private-limited",
    "name": "Balaji Wafers Private Limited",
    "brands": [
      {
        "id": "br-prod-2f4f27d5",
        "name": "Balaji Wafers",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/70deb00e-32dc-4f90-8b8d-845f2553b643_20260810-191153.png"
      }
    ]
  },
  {
    "id": "co-prod-gajrag-trading-co",
    "name": "Gajrag Trading Co",
    "brands": [
      {
        "id": "br-prod-2ac6d4db",
        "name": "Gajraj",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/cb1fbeb8-5a67-4d2c-aec9-4b3014b57e29_20260601-000024.png"
      }
    ]
  },
  {
    "id": "co-prod-gokul-krishi-udyog-pvt-ltd",
    "name": "Gokul Krishi Udyog Pvt Ltd",
    "brands": [
      {
        "id": "br-prod-79cc7cd7",
        "name": "Gokul",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/e118ae0a-66b5-4399-998b-2d50a1740207_20260601-000213.png"
      }
    ]
  },
  {
    "id": "co-prod-hitech-agricom-llp",
    "name": "Hitech Agricom Llp",
    "brands": [
      {
        "id": "br-prod-c487e2ef",
        "name": "Malai Magic",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/203de894-5eb6-42c7-8208-997941aa2783_20260601-000301.png"
      }
    ]
  },
  {
    "id": "co-prod-karani-spices",
    "name": "Karani Spices",
    "brands": [
      {
        "id": "br-prod-31792e8c",
        "name": "Karani Spices",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/549f80b4-1928-409f-a94b-4315e874e458_20260601-000446.png"
      }
    ]
  },
  {
    "id": "co-prod-karnool-rice-industries",
    "name": "Karnool Rice Industries",
    "brands": [
      {
        "id": "br-prod-55b8bd5c",
        "name": "Kurnool Rice",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/088ddcad-7ea5-48b0-a89d-7b7b561801cc_20260601-000541.png"
      }
    ]
  },
  {
    "id": "co-prod-mvr-industries",
    "name": "MVR Industries",
    "brands": [
      {
        "id": "br-prod-bff7cfb7",
        "name": "MVR Rice",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/1c06b47f-e3fa-478c-9444-7f7f74afcfdb_20260601-001046.png"
      }
    ]
  },
  {
    "id": "co-prod-maha-vishnu-rice-industries",
    "name": "Maha Vishnu Rice Industries",
    "brands": [
      {
        "id": "br-prod-e495e948",
        "name": "MV Rice",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/6bb37895-d1c1-49d7-8c8a-69726074d2d2_20260601-001126.png"
      }
    ]
  },
  {
    "id": "co-prod-mahadeva-dall-industries-private-limited",
    "name": "Mahadeva Dall Industries Private Limited",
    "brands": [
      {
        "id": "br-prod-b451847d",
        "name": "Double Horse",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/2aed2a8c-795d-4f51-b1e2-51c3af840972_20260618-105905.png"
      }
    ]
  },
  {
    "id": "co-prod-mahateja-ricemills-pvt-ltd",
    "name": "Mahateja Ricemills Pvt Ltd",
    "brands": [
      {
        "id": "br-prod-743e47fe",
        "name": "Maateja Rice",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/3eeaaf50-6f82-4227-8ea1-a4852bbd016c_20260601-001300.png"
      }
    ]
  },
  {
    "id": "co-prod-mahendra-rice-industry",
    "name": "Mahendra Rice Industry",
    "brands": [
      {
        "id": "br-prod-7fb1b01e",
        "name": "Cow Rice",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/5a5d89f6-f78a-41f9-9621-ae9f28467d07_20260601-001350.png"
      }
    ]
  },
  {
    "id": "co-prod-my-choice-rice-industries",
    "name": "My Choice Rice Industries",
    "brands": [
      {
        "id": "br-prod-1a38ed9a",
        "name": "My Choice Rice",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/0c46d12b-ae24-4618-b3f3-309d13080e79_20260601-001814.png"
      }
    ]
  },
  {
    "id": "co-prod-roxy-roller-flour-mills-pvt-ltd",
    "name": "Roxy Roller Flour Mills Pvt Ltd",
    "brands": [
      {
        "id": "br-prod-84e98db7",
        "name": "Roxy",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/05ea6f0e-93f6-4dbd-ad53-b2b08a78d4aa_20260601-001918.png"
      }
    ]
  },
  {
    "id": "co-prod-sai-jayalaxmi-rice-industries",
    "name": "Sai Jayalaxmi Rice Industries",
    "brands": [
      {
        "id": "br-prod-1ded799d",
        "name": "SJL Rice",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/75abf5df-7dd9-41d6-bf77-8433e083666a_20260601-001947.png"
      }
    ]
  },
  {
    "id": "co-prod-sharad-industries",
    "name": "Sharad Industries",
    "brands": [
      {
        "id": "br-prod-311bad37",
        "name": "Himalaya Rice",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/547c078e-a641-4b08-875b-8b6fa1c8da5b_20260601-002033.png"
      }
    ]
  },
  {
    "id": "co-prod-shree-ganesh-agencies",
    "name": "Shree Ganesh Agencies",
    "brands": [
      {
        "id": "br-prod-7c41886e",
        "name": "Prime Ravva",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/c15d8a85-24d2-4642-8bb3-d31f8d9ea186_20260601-002138.png"
      },
      {
        "id": "br-prod-77e413c1",
        "name": "Zuri Rice",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/4a250914-d1af-43a7-8cca-adb4c1ac2d73_20260601-002138.png"
      }
    ]
  },
  {
    "id": "co-prod-shree-renuka-sugars-limited",
    "name": "Shree Renuka Sugars Limited",
    "brands": [
      {
        "id": "br-prod-883d49b0",
        "name": "Madhur",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/b9f9fc4d-dc17-4232-aab0-c5e564da328a_20260530-184032.png"
      }
    ]
  },
  {
    "id": "co-prod-shri-balaji-bajrang-industries",
    "name": "Shri Balaji Bajrang Industries",
    "brands": [
      {
        "id": "br-prod-4c728bee",
        "name": "Lal Quila",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/09682023-f3a2-4b58-9901-da7fcb760454_20260601-002337.png"
      }
    ]
  },
  {
    "id": "co-prod-smaya-industries",
    "name": "Smaya Industries",
    "brands": [
      {
        "id": "br-prod-9fa30f44",
        "name": "Nature Guru",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/6949ee7b-a1bc-4a5a-b79a-11be782243f8_20260601-002420.png"
      }
    ]
  },
  {
    "id": "co-prod-south-india-krishna-oil-and-fats-pvt",
    "name": "South India Krishna Oil & Fats Pvt",
    "brands": [
      {
        "id": "br-prod-e9666a4a",
        "name": "Rajni Gold",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/7beac01e-ed9c-4a22-85dc-0568ac7b1798_20260601-002504.png"
      }
    ]
  },
  {
    "id": "co-prod-sri-krishna-rice-industries",
    "name": "Sri Krishna Rice Industries",
    "brands": [
      {
        "id": "br-prod-6c2fa933",
        "name": "Sri Krishna Rice",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/68a40092-2237-41cf-ba78-5006cd06c9fb_20260601-002546.png"
      }
    ]
  },
  {
    "id": "co-prod-sri-lalitha-enterprises-industries-p-lim",
    "name": "Sri Lalitha Enterprises Industries P Limited",
    "brands": [
      {
        "id": "br-prod-2f7adab0",
        "name": "Netaji",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/04c17c33-348b-48bb-9ce5-417715aaff30_20260601-002714.png"
      },
      {
        "id": "br-prod-57f55957",
        "name": "Sri Lalitha",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/b5cfbfe4-e6c8-4c0f-9d7c-7f85595f3e5e_20260601-002714.png"
      }
    ]
  },
  {
    "id": "co-prod-sri-maatha-sai-balali-rice-industries",
    "name": "Sri Maatha Sai Balali Rice Industries",
    "brands": [
      {
        "id": "br-prod-4d108253",
        "name": "SMS Rice",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/8c33812a-087d-401e-be23-32a3bc762d42_20260601-002747.png"
      }
    ]
  },
  {
    "id": "co-prod-sri-rk-modern-rice-mill",
    "name": "Sri Rk Modern Rice Mill",
    "brands": [
      {
        "id": "br-prod-568c1e82",
        "name": "Sri Rk Rice",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/c39d90bd-7fa9-4352-b911-c9a97065c20c_20260923-171455.jpg"
      }
    ]
  },
  {
    "id": "co-prod-sri-sambadiva-industries",
    "name": "Sri Sambadiva Industries",
    "brands": [
      {
        "id": "br-prod-def24390",
        "name": "SSI Rice",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/c99ba2be-bca8-4cb8-9696-fa57cc81c1e0_20260601-002827.png"
      }
    ]
  },
  {
    "id": "co-prod-swad-foods-private-limited",
    "name": "Swad Foods Private Limited",
    "brands": [
      {
        "id": "br-prod-c33b8cf3",
        "name": "Naturralle Rice",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/056965c2-5b54-41b8-b3e1-a437cd2ddae5_20260606-225803.jpg"
      }
    ]
  },
  {
    "id": "co-prod-vijayalakshmi-dall-mill",
    "name": "Vijayalakshmi Dall Mill",
    "brands": [
      {
        "id": "br-prod-18679e9c",
        "name": "Vijayalakshmi",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/ff59742c-a1a1-4730-9f80-63fc23fadba9_20260601-003925.png"
      }
    ]
  },
  {
    "id": "co-prod-delite-oven-fresh",
    "name": "Delite Oven Fresh",
    "brands": [
      {
        "id": "br-prod-90adaa0d",
        "name": "Lina",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/93c0f5d9-02e2-4625-8aac-a8937cb539bb_20260905-120702.png"
      }
    ]
  },
  {
    "id": "co-prod-mformillet-foods-pvt-ltd",
    "name": "Mformillet Foods Pvt Ltd",
    "brands": [
      {
        "id": "br-prod-8e16117c",
        "name": "Troo Good",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/1b414c9a-3b10-4fbf-82f8-468debffe530_20260905-120836.jpg"
      }
    ]
  },
  {
    "id": "co-prod-rysa-veda-ventures-private-limited",
    "name": "Rysa Veda Ventures Private Limited",
    "brands": [
      {
        "id": "br-prod-20256c1e",
        "name": "Hydrate X",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/cee2a467-ca27-44b5-b42d-92fa3377a2fe_20260905-121029.png"
      }
    ]
  },
  {
    "id": "co-prod-tejas-food-industrise-llp",
    "name": "Tejas Food Industrise LLP",
    "brands": [
      {
        "id": "br-prod-f65d9386",
        "name": "Swetha Telugu Foods",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/e5823e45-a947-4884-97d8-1b975fe71a73_20260905-120443.jpg"
      }
    ]
  },
  {
    "id": "co-prod-anoos-electrolysis-and-obesity-pvt-ltd",
    "name": "Anoos Electrolysis & Obesity Pvt. Ltd.",
    "brands": [
      {
        "id": "br-prod-3e4e3b7a",
        "name": "Anoos",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/febbcc4e-f421-49a9-90d0-0d47b8a92232_20260727-212923.jpg"
      }
    ]
  },
  {
    "id": "co-prod-apis-india-limited",
    "name": "Apis India Limited",
    "brands": [
      {
        "id": "br-prod-1b05c505",
        "name": "Apis",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/6c3080b7-ae9e-42ec-9f2c-5fb948db9697_20260727-213047.jpg"
      }
    ]
  },
  {
    "id": "co-prod-aravind-laboratories",
    "name": "Aravind Laboratories",
    "brands": [
      {
        "id": "br-prod-db90b366",
        "name": "Dazller",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/b8f9cde3-c919-4075-804e-8bb5ad7311d3_20260727-215500.jpg"
      },
      {
        "id": "br-prod-173ccb25",
        "name": "Eyetex",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/69ba20e6-bcd3-4206-843f-03299e107ab2_20260727-215500.jpg"
      }
    ]
  },
  {
    "id": "co-prod-argus-cosmetics-limited",
    "name": "Argus Cosmetics Limited",
    "brands": [
      {
        "id": "br-prod-7d564400",
        "name": "Z Magnetism",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/b6ec48e4-1155-43ea-a985-793d0d946777_20260727-220514.jpg"
      }
    ]
  },
  {
    "id": "co-prod-dodla-dairy-limited",
    "name": "Dodla Dairy Limited",
    "brands": [
      {
        "id": "br-prod-6a12abcd",
        "name": "Dodla",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/6e3777fd-36cc-43b4-9aad-fd66da3e0482_20260727-214456.png"
      }
    ]
  },
  {
    "id": "co-prod-parimal-mandir",
    "name": "Parimal Mandir",
    "brands": [
      {
        "id": "br-prod-bb96b2cd",
        "name": "Bharat Vasi",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/0ecc5dee-91a2-4f40-b044-07354cdeee01_20260727-213525.jpg"
      },
      {
        "id": "br-prod-0aeda772",
        "name": "Parimal",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/cf86cdc0-83c5-4e2a-89a3-8d8ad227f28f_20260727-213525.jpg"
      }
    ]
  },
  {
    "id": "co-prod-rkrm-international-products-pvt-ltd",
    "name": "RKRM International Products Pvt. Ltd.",
    "brands": [
      {
        "id": "br-prod-ced6cf39",
        "name": "RK",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/56f05cc8-e1b3-4504-8afc-538d148fa23b_20260727-220100.jpg"
      }
    ]
  },
  {
    "id": "co-prod-tiesar-personal-care-pvt-ltd",
    "name": "Tiesar Personal Care Pvt. Ltd.",
    "brands": [
      {
        "id": "br-prod-fd8e5ccb",
        "name": "Gokul Santol",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/a3004b22-d44a-4458-934a-5cabbc254ddd_20260727-215853.jpg"
      }
    ]
  },
  {
    "id": "co-prod-godesi-mandi-private-limited",
    "name": "Godesi Mandi Private Limited",
    "brands": [
      {
        "id": "br-prod-e4c9a182",
        "name": "Go Desi",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/e413a0f3-121f-4d55-958a-96e12a9c211e_20260828-153646.png"
      }
    ]
  },
  {
    "id": "co-prod-laser-shaving-india-private-limited",
    "name": "Laser Shaving India Private Limited",
    "brands": [
      {
        "id": "br-prod-9eb8a6d4",
        "name": "Gallant",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/c23654c6-2284-4f00-986a-e490aa76055d_20260828-154505.png"
      },
      {
        "id": "br-prod-b4ec7325",
        "name": "Laser",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/7dae01ed-2ef4-4656-ad9e-d25d8bdd2fdc_20260828-154505.png"
      },
      {
        "id": "br-prod-430baf36",
        "name": "Shakti",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/acc1804b-75ba-4d90-a3d0-89e25a26b7d6_20260923-132702.jpg"
      },
      {
        "id": "br-prod-cd7d18cd",
        "name": "Tez",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/780167fc-70f3-4688-bde1-5e6675c5b9c8_20260923-132702.jpg"
      },
      {
        "id": "br-prod-c946e2d9",
        "name": "Topaz",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/3613f24d-403f-434f-bba2-e89f0292c15a_20260923-132702.jpg"
      }
    ]
  },
  {
    "id": "co-prod-s-c-johnson-and-son-private-limited",
    "name": "S.C. Johnson & Son Private Limited",
    "brands": [
      {
        "id": "br-prod-33980453",
        "name": "All Out",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/c873c976-6ec0-4188-8da8-b2bc023105e1_20260731-170136.jpg"
      },
      {
        "id": "br-prod-2c4b71bd",
        "name": "Baygon",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/c31ea95a-56b6-4f1a-a443-9048bc584db1_20260731-170136.jpg"
      },
      {
        "id": "br-prod-53386e51",
        "name": "Glade",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/07986590-aebc-41d4-b016-4dbeaa8c51ad_20260731-170136.jpg"
      },
      {
        "id": "br-prod-d9eba7ed",
        "name": "Kiwi",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/27f8e4e3-66c9-4e0e-bc78-74241d87bc5b_20260731-170136.jpg"
      },
      {
        "id": "br-prod-0b666509",
        "name": "Mr Muscle",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/aea18cf9-049e-41da-9574-23b169c9548c_20260731-170136.jpg"
      }
    ]
  },
  {
    "id": "co-prod-vcare-pharcos",
    "name": "VCare Pharcos",
    "brands": [
      {
        "id": "br-prod-fe8f77d3",
        "name": "VCare",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/cfd797b8-88c6-4d0b-9b2f-ec6a5e30d098_20260923-150111.jpg"
      }
    ]
  },
  {
    "id": "co-prod-vvd-and-sons-pvt-ltd",
    "name": "VVD and Sons Pvt Ltd",
    "brands": [
      {
        "id": "br-prod-9c3e7b08",
        "name": "VVD",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/615da388-dc45-4375-90f6-a366596a324b_20260922-182722.jpg"
      }
    ]
  },
  {
    "id": "co-prod-lt-foods-ltd",
    "name": "LT Foods Ltd.",
    "brands": [
      {
        "id": "br-prod-f2023013",
        "name": "Daawat",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/32cbc948-7692-49b3-8eab-33f56a13118b_20260803-150610.png"
      }
    ]
  },
  {
    "id": "co-prod-sri-sarwo-natraj-agro-india-private-limi",
    "name": "Sri Sarwo Natraj Agro India Private Limited",
    "brands": [
      {
        "id": "br-prod-c5428ae4",
        "name": "Gold Field",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/4fee6272-0397-441e-a495-f8f3f090094a_20260918-002807.png"
      },
      {
        "id": "br-prod-6abe5833",
        "name": "Sri Natraj",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/d248c45c-2465-41c0-9ef3-01ea7a85eeba_20260918-002807.png"
      }
    ]
  },
  {
    "id": "co-prod-n-ranga-rao-and-sons-private-limited",
    "name": "N. Ranga Rao & Sons Private Limited",
    "brands": [
      {
        "id": "br-prod-a6be62e0",
        "name": "Cycle",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/77a8fd37-7d34-4fe6-b2e6-cd47a46d8901_20260530-182127.png"
      }
    ]
  },
  {
    "id": "co-prod-sri-ganesh-balaji-lakhdaatr-oil",
    "name": "Sri Ganesh Balaji Lakhdaatr Oil",
    "brands": [
      {
        "id": "br-prod-4eba4249",
        "name": "Deepking",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/c7281c9a-c97d-4a9f-90ee-2275085c4d6a_20260606-212311.png"
      }
    ]
  },
  {
    "id": "co-prod-cavinkare-pvt-ltd",
    "name": "CavinKare Pvt Ltd",
    "brands": [
      {
        "id": "br-prod-9b5f4f1c",
        "name": "Cavin's",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/4ccab9ab-feac-431a-9304-78d22a0f0d12_20260910-175028.png"
      },
      {
        "id": "br-prod-48efbb53",
        "name": "Chik",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/533fe401-7f14-4b31-865d-e966464c4ee3_20260910-175028.png"
      },
      {
        "id": "br-prod-4254d55e",
        "name": "Indica",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/d03ded48-b732-4af7-8adb-7cfdcbd27af3_20260910-175028.png"
      },
      {
        "id": "br-prod-7166e5b1",
        "name": "Karthika",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/ac6d18a4-cc15-4528-909c-5dd58d2280f5_20260910-175028.png"
      },
      {
        "id": "br-prod-9874bb6b",
        "name": "Maa",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/05126689-57be-4de5-b3c7-62f58ee981f9_20260910-175028.png"
      },
      {
        "id": "br-prod-2a72f5f0",
        "name": "Meera",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/7488fc92-84ce-4e06-acda-501c625295a7_20260910-175028.png"
      },
      {
        "id": "br-prod-c241fa0f",
        "name": "Nyle",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/4dcebe23-1042-46df-849b-544ae24259d0_20260910-175028.png"
      },
      {
        "id": "br-prod-01c37cac",
        "name": "Spinz",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/3d8686f9-dac7-4488-a98d-b72cde9fd14b_20260910-175028.png"
      }
    ]
  },
  {
    "id": "co-prod-unicharm-india-private-limited",
    "name": "Unicharm India Private Limited.",
    "brands": [
      {
        "id": "br-prod-acdc5cef",
        "name": "Lifree",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/a860d5d9-78ea-4ec8-b6d1-d509cda76922_20260910-175719.png"
      },
      {
        "id": "br-prod-e3b7e407",
        "name": "MamyPoko",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/d0a582cc-f45a-4514-b314-2564dae75a9a_20260910-175719.png"
      },
      {
        "id": "br-prod-37b05e4f",
        "name": "Sofy",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/99cb310f-e101-40c7-b743-163e500a8c6a_20260910-175719.png"
      }
    ]
  },
  {
    "id": "co-prod-parle-products-private-ltd",
    "name": "Parle Products Private Ltd",
    "brands": [
      {
        "id": "br-prod-ea88bc75",
        "name": "2 in 1 Eclairs",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/e86e9527-8ca7-45a2-a151-6b3c79ff65f4_20260923-131748.png"
      },
      {
        "id": "br-prod-b6811b28",
        "name": "20-20",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/1cf3e10c-4657-41bf-bee2-79ee9e4ec2e4_20260825-121050.jpg"
      },
      {
        "id": "br-prod-b4bdbb00",
        "name": "Fab!",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/69f73222-8dd0-4b82-961c-52fcf31e7ebc_20260825-121050.jpg"
      },
      {
        "id": "br-prod-69fd8a25",
        "name": "Full 2",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/fb27be33-af1b-4f0a-aeb2-459c5537f6ba_20260923-131748.png"
      },
      {
        "id": "br-prod-a3eba3c2",
        "name": "Funtoosh",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/c17d08c3-1e99-4807-8b66-b54d61e540f7_20260923-131748.png"
      },
      {
        "id": "br-prod-2397ce3a",
        "name": "Fusion",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/55b3812a-de2e-4682-b3c4-fa3f7bc658b6_20260923-131748.png"
      },
      {
        "id": "br-prod-e858039b",
        "name": "Happy Happy",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/b5d9d266-23e5-4a30-b3d8-769d11412c70_20260825-121050.jpg"
      },
      {
        "id": "br-prod-a19fe2e8",
        "name": "Hide & Seek",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/ae2db1f1-d13e-4961-aea5-f5414e06be6c_20260825-121050.jpg"
      },
      {
        "id": "br-prod-2ee2b804",
        "name": "Kapi Candy",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/148632c0-cfbc-40c2-beca-bc76b6b14aa1_20260825-121050.png"
      },
      {
        "id": "br-prod-2af3c6e2",
        "name": "Kismi",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/a02ac5af-b5c7-4b2c-8229-fbff5f5d1f55_20260825-121050.jpg"
      },
      {
        "id": "br-prod-045497f9",
        "name": "Krackjack",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/83f098b3-485b-4688-8b0e-2161889378e8_20260825-121050.jpg"
      },
      {
        "id": "br-prod-1f4ac325",
        "name": "Londonderry",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/6d156e30-e47b-4b95-928d-f529bdb67a27_20260825-121050.png"
      },
      {
        "id": "br-prod-df196f99",
        "name": "Magix",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/fa535439-a4cd-4233-9658-a79eb3e74fa7_20260825-121050.jpg"
      },
      {
        "id": "br-prod-254e20b3",
        "name": "Marie",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/7a880a84-3f13-4f29-bc50-97232b4ae7e0_20260825-121050.jpg"
      },
      {
        "id": "br-prod-5bfcf14f",
        "name": "Mazelo",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/94d1ec54-3d25-4c5e-8a77-e96944a34d59_20260923-131748.png"
      },
      {
        "id": "br-prod-2474135c",
        "name": "Melody",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/2770a057-485c-4bf6-b4f7-49c4640c8461_20260923-131748.png"
      },
      {
        "id": "br-prod-fafbac9d",
        "name": "Milano",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/63a0da1c-40bb-466d-a14c-b53ad4819b07_20260825-121050.jpg"
      },
      {
        "id": "br-prod-e8a027d8",
        "name": "Milk Shakti",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/56afee11-7f87-49a1-9ded-c392ed7dc409_20260825-121050.jpg"
      },
      {
        "id": "br-prod-17b48867",
        "name": "Monaco",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/4a0a5e30-05b2-49c4-80f4-778205ea9852_20260825-121050.jpg"
      },
      {
        "id": "br-prod-3aab404e",
        "name": "Nutricrunch",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/bcc30a6f-9c75-4edc-8cd1-45cfd6dae110_20260825-121050.jpg"
      },
      {
        "id": "br-prod-aba6b866",
        "name": "Parle",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/8ba385c5-8834-44bf-a6f2-3d20219956e5_20260825-121050.png"
      },
      {
        "id": "br-prod-e586b325",
        "name": "Parle-G",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/5e147d32-0d7e-42f4-b14c-d35b63b77c63_20260825-121050.jpg"
      },
      {
        "id": "br-prod-10a75585",
        "name": "Rik Rak",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/e720ea17-e26e-44e5-bd5b-0e0cf10550f1_20260923-131748.png"
      }
    ]
  },
  {
    "id": "co-prod-gujarat-tea-processors-and-packers-ltd",
    "name": "Gujarat Tea Processors & Packers Ltd",
    "brands": [
      {
        "id": "br-prod-8baee144",
        "name": "Wagh Bakri",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/83c605d2-6f1d-4973-8192-90ebe68384a0_20260611-174408.png"
      }
    ]
  },
  {
    "id": "co-prod-hamdard-foods-india",
    "name": "Hamdard Foods India",
    "brands": [
      {
        "id": "br-prod-3165068c",
        "name": "Hamdard",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/2bc1e76e-3a1c-48f4-86b9-ba7dc713145b_20260611-173959.png"
      }
    ]
  },
  {
    "id": "co-prod-reliance-consumer-products-limited-rcpl",
    "name": "Reliance Consumer Products Limited (RCPL)",
    "brands": [
      {
        "id": "br-prod-83cb6e93",
        "name": "Reliance",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/91d05665-5b12-4a38-b319-ef7f410c9fab_20260611-174226.png"
      }
    ]
  },
  {
    "id": "co-prod-rudra-industries",
    "name": "Rudra Industries",
    "brands": [
      {
        "id": "br-prod-b1ada7e2",
        "name": "Mos-Quit-Go.",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/3116bb0d-627e-4f82-9376-39dff1b70c21_20260923-134308.jpg"
      }
    ]
  },
  {
    "id": "co-prod-milky-mist-dairy-food-limited",
    "name": "Milky Mist Dairy Food Limited",
    "brands": [
      {
        "id": "br-prod-98c98bf2",
        "name": "Milky Mist",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/b205d94e-f13f-418c-ba75-e478ecdc6354_20260612-144840.png"
      }
    ]
  },
  {
    "id": "co-prod-rehoboth-industries",
    "name": "Rehoboth Industries",
    "brands": [
      {
        "id": "br-prod-08763848",
        "name": "G D",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/fff1fc97-6c65-494a-9fda-1156e07b45d3_20260530-183435.png"
      }
    ]
  },
  {
    "id": "co-prod-sneha-farms",
    "name": "Sneha Farms",
    "brands": [
      {
        "id": "br-prod-89974ea0",
        "name": "Sneha",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/e20affc5-7f4b-4fd1-871c-c322287b4e14_20260530-184316.png"
      },
      {
        "id": "br-prod-4c3b0d9e",
        "name": "Sukhibhava",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/ecd8afcd-5427-49d6-8390-42d525e5ab39_20260606-224853.jpg"
      }
    ]
  },
  {
    "id": "co-prod-himalaya-wellness-company",
    "name": "Himalaya Wellness Company.",
    "brands": [
      {
        "id": "br-prod-08ececd0",
        "name": "Himalaya",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/d9aa939b-3a01-49d2-9f84-779c576c7751_20260704-155542.png"
      }
    ]
  },
  {
    "id": "co-prod-wipro-enterprises-p-limited",
    "name": "Wipro Enterprises (P) Limited",
    "brands": [
      {
        "id": "br-prod-edefdb86",
        "name": "Wipro",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/146baabb-5d41-4dd6-9e7e-4c5674d9a3d7_20260704-154957.png"
      }
    ]
  },
  {
    "id": "co-prod-anchor-consumer-product-pvt-ltd",
    "name": "Anchor Consumer Product Pvt. Ltd.",
    "brands": [
      {
        "id": "br-prod-73987179",
        "name": "Anchor",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/31c51715-938e-41a4-b984-9ca056c9e75d_20260924-113917.png"
      }
    ]
  },
  {
    "id": "co-prod-fitday-private-limited",
    "name": "Fitday Private Limited",
    "brands": [
      {
        "id": "br-prod-50915673",
        "name": "Fitday",
        "imageUrl": "https://eb2b-docs.blr1.digitaloceanspaces.com/seller_portal/brands/a69b75c5-fb80-414c-9db8-073d8bfbd4db_20260924-114123.jpg"
      }
    ]
  }
];
