// GENERATED by build-prod-replica-seed.cjs — do not edit by hand.
// Production companies referenced by the replicated delivery beats.
// (Adani Wilmar Limited, Gemini Edibles and ITC Limited reuse the
// pre-existing catalog ids co-adani / co-freedom / co-itc.)
export const PROD_REPLICA_COMPANIES: { id: string; name: string }[] = [
  {
    "id": "co-prod-swastik-mirch-store",
    "name": "Swastik Mirch Store"
  },
  {
    "id": "co-prod-anoos-electrolysis-and-obesity-pvt-ltd",
    "name": "Anoos Electrolysis & Obesity Pvt. Ltd."
  },
  {
    "id": "co-prod-apis-india-limited",
    "name": "Apis India Limited"
  },
  {
    "id": "co-prod-aravind-laboratories",
    "name": "Aravind Laboratories"
  },
  {
    "id": "co-prod-argus-cosmetics-limited",
    "name": "Argus Cosmetics Limited"
  },
  {
    "id": "co-prod-aswini-homeo-and-ayurvedic-products-pvt-",
    "name": "Aswini Homeo & Ayurvedic Products Pvt. Ltd."
  },
  {
    "id": "co-prod-dey-s-medical-stores-pvt-ltd",
    "name": "Dey'S Medical Stores Pvt. Ltd"
  },
  {
    "id": "co-prod-dodla-dairy-limited",
    "name": "Dodla Dairy Limited"
  },
  {
    "id": "co-prod-henna-industries-pvt-ltd",
    "name": "Henna Industries Pvt Ltd."
  },
  {
    "id": "co-prod-karnataka-soaps-and-detergents-limited",
    "name": "Karnataka Soaps And Detergents Limited"
  },
  {
    "id": "co-prod-mayuri-chemicals-private-limited",
    "name": "Mayuri Chemicals Private Limited"
  },
  {
    "id": "co-prod-parimal-mandir",
    "name": "Parimal Mandir"
  },
  {
    "id": "co-prod-rkrm-international-products-pvt-ltd",
    "name": "RKRM International Products Pvt. Ltd."
  },
  {
    "id": "co-prod-tiesar-personal-care-pvt-ltd",
    "name": "Tiesar Personal Care Pvt. Ltd."
  },
  {
    "id": "co-prod-b-p-oil-mills-limited",
    "name": "B P Oil Mills Limited"
  },
  {
    "id": "co-prod-aak-kamani-private-limited",
    "name": "Aak Kamani Private Limited"
  },
  {
    "id": "co-prod-ami-oil-mill",
    "name": "Ami Oil Mill"
  },
  {
    "id": "co-prod-bolas-agro-private-limited",
    "name": "Bolas Agro Private Limited"
  },
  {
    "id": "co-prod-kirti-oil-industries-private-limited",
    "name": "KIRTI oil industries private limited"
  },
  {
    "id": "co-prod-kamani-oil-industries",
    "name": "Kamani Oil Industries"
  },
  {
    "id": "co-prod-komal-oil-private-limited",
    "name": "Komal Oil Private Limited"
  },
  {
    "id": "co-prod-marico-limited",
    "name": "Marico Limited"
  },
  {
    "id": "co-prod-r-r-oomerbhoy-pvt-ltd",
    "name": "R R Oomerbhoy Pvt Ltd"
  },
  {
    "id": "co-prod-raj-oil-mills-ltd",
    "name": "RAJ OIL MILLS LTD"
  },
  {
    "id": "co-prod-vimal-oil-and-foods-ltd",
    "name": "Vimal Oil & Foods Ltd."
  },
  {
    "id": "co-prod-vitthal-oil-industries",
    "name": "Vitthal Oil Industries"
  },
  {
    "id": "co-prod-emami-limited",
    "name": "Emami Limited"
  },
  {
    "id": "co-prod-mvm-synergy-solutions-llp",
    "name": "Mvm Synergy Solutions LLP"
  },
  {
    "id": "co-prod-western-india-bakers-pvt-ltd",
    "name": "Western India Bakers Pvt.Ltd."
  },
  {
    "id": "co-prod-colgate-palmolive",
    "name": "Colgate-Palmolive"
  },
  {
    "id": "co-prod-international-flavours-and-fragrances-in",
    "name": "International Flavours & Fragrances India Private Limited."
  },
  {
    "id": "co-prod-lion-dates-impex-p-ltd",
    "name": "Lion Dates Impex (P) Ltd"
  },
  {
    "id": "co-prod-msk-flavours",
    "name": "Msk Flavours."
  },
  {
    "id": "co-prod-peppergami-food-labs-private-limited",
    "name": "PEPPERGAMI FOOD LABS PRIVATE LIMITED."
  },
  {
    "id": "co-prod-raghav-lifestyle-products",
    "name": "Raghav Lifestyle Products"
  },
  {
    "id": "co-prod-sgr-777-foods-private-limited",
    "name": "SGR (777) Foods Private Limited."
  },
  {
    "id": "co-prod-weikfield-foods-private-limited",
    "name": "Weikfield Foods Private Limited."
  },
  {
    "id": "co-prod-3f-industries-ltd",
    "name": "3f Industries Ltd"
  },
  {
    "id": "co-prod-emami-agrotech-limited",
    "name": "Emami Agrotech Limited"
  },
  {
    "id": "co-prod-fourtune-agri-solutions",
    "name": "Fourtune Agri Solutions"
  },
  {
    "id": "co-prod-healthy-heart-foods",
    "name": "Healthy Heart Foods"
  },
  {
    "id": "co-prod-kedia-agro",
    "name": "Kedia Agro"
  },
  {
    "id": "co-prod-magnum-enterprises",
    "name": "Magnum Enterprises"
  },
  {
    "id": "co-prod-navabhart-limited",
    "name": "Navabhart Limited"
  },
  {
    "id": "co-prod-patanjali-foods-limited",
    "name": "Patanjali Foods Limited"
  },
  {
    "id": "co-prod-pattabi-agro-foods-pvt-ltd",
    "name": "Pattabi agro foods Pvt Ltd"
  },
  {
    "id": "co-prod-santhoshimatha-edible-oils-refinery-pvt-",
    "name": "Santhoshimatha Edible Oils Refinery Pvt. Ltd"
  },
  {
    "id": "co-prod-shree-gajanan-industries",
    "name": "Shree Gajanan Industries"
  },
  {
    "id": "co-prod-sri-tulasi-industries",
    "name": "Sri Tulasi Industries"
  },
  {
    "id": "co-prod-himalaya-wellness-company",
    "name": "Himalaya Wellness Company."
  },
  {
    "id": "co-prod-vanesa-care-pvt-ltd",
    "name": "Vanesa Care Pvt. Ltd."
  },
  {
    "id": "co-prod-wipro-enterprises-p-limited",
    "name": "Wipro Enterprises (P) Limited"
  },
  {
    "id": "co-prod-aadishwar-organics-private-limited",
    "name": "Aadishwar Organics Private Limited"
  },
  {
    "id": "co-prod-adyar-ananda-bhavan-sweets-india-private",
    "name": "Adyar Ananda Bhavan Sweets India Private Limited"
  },
  {
    "id": "co-prod-allied-natural-product",
    "name": "Allied Natural Product"
  },
  {
    "id": "co-prod-ambica-agarbathies-aroma-and-industries-",
    "name": "Ambica Agarbathies Aroma & Industries Limited"
  },
  {
    "id": "co-prod-buy-happy-marketing-llp",
    "name": "Buy Happy Marketing Llp"
  },
  {
    "id": "co-prod-duracell-inc",
    "name": "Duracell Inc."
  },
  {
    "id": "co-prod-dwibhashi-bapanna-ayurveda-nilayam-pvt-l",
    "name": "Dwibhashi Bapanna Ayurveda Nilayam Pvt. Ltd."
  },
  {
    "id": "co-prod-harvesta-farming-private-limited",
    "name": "Harvesta Farming Private Limited"
  },
  {
    "id": "co-prod-haw-par-healthcare-limited",
    "name": "Haw Par Healthcare Limited"
  },
  {
    "id": "co-prod-hygienic-research-institute-private-limi",
    "name": "Hygienic Research Institute Private Limited"
  },
  {
    "id": "co-prod-laljee-godhoo-and-co",
    "name": "Laljee Godhoo & Co."
  },
  {
    "id": "co-prod-midas-hygiene-industries-pvt-ltd",
    "name": "Midas Hygiene Industries Pvt. Ltd"
  },
  {
    "id": "co-prod-nextg-apex-india-pvt-ltd",
    "name": "Nextg Apex India Pvt. Ltd."
  },
  {
    "id": "co-prod-sachin-traders",
    "name": "Sachin Traders"
  },
  {
    "id": "co-prod-sesa-care-pvt-ltd",
    "name": "Sesa Care Pvt. Ltd."
  },
  {
    "id": "co-prod-the-national-tea-depot",
    "name": "The National Tea Depot."
  },
  {
    "id": "co-prod-vicco-laboratories",
    "name": "Vicco Laboratories"
  },
  {
    "id": "co-prod-vijaya-chemicals-and-toilet-works-telang",
    "name": "Vijaya Chemicals & Toilet Works Telangana"
  },
  {
    "id": "co-prod-grb-dairy-foods-pvt-ltd",
    "name": "GRB DAIRY FOODS PVT.LTD."
  },
  {
    "id": "co-prod-marino-food-products-pvt-ltd",
    "name": "Marino Food Products Pvt Ltd"
  },
  {
    "id": "co-prod-sln-coffee-pvt-ltd",
    "name": "SLN Coffee Pvt. Ltd"
  },
  {
    "id": "co-prod-swastiks-masalas-pickles-and-food-produc",
    "name": "Swastiks Masalas Pickles & Food Products pvt ltd"
  },
  {
    "id": "co-prod-milky-mist-dairy-food-limited",
    "name": "Milky Mist Dairy Food Limited"
  },
  {
    "id": "co-prod-rudra-industries",
    "name": "Rudra Industries"
  },
  {
    "id": "co-prod-reliance-consumer-products-limited-rcpl",
    "name": "Reliance Consumer Products Limited (RCPL)"
  },
  {
    "id": "co-prod-gujarat-tea-processors-and-packers-ltd",
    "name": "Gujarat Tea Processors & Packers Ltd"
  },
  {
    "id": "co-prod-hamdard-foods-india",
    "name": "Hamdard Foods India"
  },
  {
    "id": "co-prod-sri-gantasala-foods",
    "name": "Sri Gantasala Foods"
  },
  {
    "id": "co-prod-e-i-d-parry-india-ltd",
    "name": "E I D Parry India Ltd"
  },
  {
    "id": "co-prod-gajrag-trading-co",
    "name": "Gajrag Trading Co"
  },
  {
    "id": "co-prod-gokul-krishi-udyog-pvt-ltd",
    "name": "Gokul Krishi Udyog Pvt Ltd"
  },
  {
    "id": "co-prod-hitech-agricom-llp",
    "name": "Hitech Agricom Llp"
  },
  {
    "id": "co-prod-karani-spices",
    "name": "Karani Spices"
  },
  {
    "id": "co-prod-karnool-rice-industries",
    "name": "Karnool Rice Industries"
  },
  {
    "id": "co-prod-lohiya-edible-oils-pvt-ltd",
    "name": "Lohiya Edible Oils Pvt Ltd"
  },
  {
    "id": "co-prod-mvr-industries",
    "name": "MVR Industries"
  },
  {
    "id": "co-prod-maha-vishnu-rice-industries",
    "name": "Maha Vishnu Rice Industries"
  },
  {
    "id": "co-prod-ambati-subbanna-and-co",
    "name": "Ambati Subbanna & Co"
  },
  {
    "id": "co-prod-patanjali-ayurved-limited",
    "name": "Patanjali Ayurved Limited"
  },
  {
    "id": "co-prod-shree-saraiwwalaa-aggrr-refineries-limit",
    "name": "Shree Saraiwwalaa Aggrr Refineries Limited"
  },
  {
    "id": "co-prod-south-india-krishna-oil-and-fats-pvt",
    "name": "South India Krishna Oil & Fats Pvt"
  },
  {
    "id": "co-prod-sri-ganesh-balaji-lakhdaatr-oil",
    "name": "Sri Ganesh Balaji Lakhdaatr Oil"
  },
  {
    "id": "co-prod-rehoboth-industries",
    "name": "Rehoboth Industries"
  },
  {
    "id": "co-prod-shree-renuka-sugars-limited",
    "name": "Shree Renuka Sugars Limited"
  },
  {
    "id": "co-prod-sneha-farms",
    "name": "Sneha Farms"
  },
  {
    "id": "co-prod-karkhana-zinda-tilismath-llp",
    "name": "Karkhana Zinda Tilismath LLP"
  },
  {
    "id": "co-prod-orkla-india-private-limited",
    "name": "Orkla India Private Limited"
  },
  {
    "id": "co-prod-n-ranga-rao-and-sons-private-limited",
    "name": "N. Ranga Rao & Sons Private Limited"
  },
  {
    "id": "co-prod-ushodaya-enterprises-private-limited",
    "name": "Ushodaya Enterprises Private Limited"
  },
  {
    "id": "co-prod-bambino-agro-industries-ltd",
    "name": "Bambino Agro Industries Ltd"
  },
  {
    "id": "co-prod-gh-industries",
    "name": "GH Industries"
  },
  {
    "id": "co-prod-msr-products",
    "name": "MSR Products"
  },
  {
    "id": "co-prod-rajam-industries-private-limited",
    "name": "Rajam Industries Private Limited"
  },
  {
    "id": "co-prod-v-r-enterprises",
    "name": "V R Enterprises"
  },
  {
    "id": "co-prod-ava-cholayil-health-care-private-limited",
    "name": "AVA Cholayil Health Care Private Limited"
  }
];
